export const NAME = 'wehoop'
export const NAME_AND_DOMAIN = 'wehoop'
export const BASE_URL = 'https://saiemgilani.github.io/wehoop'
export const GH_USER = 'saiemgilani'
export const GH_REPO = 'wehoop'
export const DEPLOYMENTS_URL = 'https://api.github.com/repos/saiemgilani/wehoop/deployments'
