## wehoop_schemas.R
## -------------------
## Shared column schemas referenced via [schema_name] links from
## multiple wehoop functions whose result-set tables are byte-identical.
## Generated by a one-time dedup pass (tools/docs/markdown_man_table_helper.R
## skips these topics on re-augmentation -- see the SKIP_SCHEMA_TOPICS guard
## in that file). Docs-only: no exports, `@keywords internal` throughout.

#' Shared column schema: basketball load wbb game rosters schema
#'
#' Columns shared verbatim across: load_wbb_game_rosters, load_wnba_game_rosters.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    game_id \tab character \tab Unique game identifier. \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    team_id \tab character \tab Unique team identifier. \cr
#'    athlete_id \tab character \tab Unique athlete identifier (ESPN). \cr
#'    athlete_display_name \tab character \tab Athlete display name (full). \cr
#'    athlete_position \tab character \tab Athlete position. \cr
#'    athlete_jersey \tab character \tab Athlete jersey number. \cr
#'    starter \tab logical \tab TRUE if the player was in the starting lineup; FALSE otherwise. \cr
#'    did_not_play \tab logical \tab TRUE if the player did not appear in the game. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name basketball_load_wbb_game_rosters_schema
#' @keywords internal
NULL

#' Shared column schema: basketball load wbb officials schema
#'
#' Columns shared verbatim across: load_wbb_officials, load_wnba_officials.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    game_id \tab character \tab Unique game identifier. \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    official_id \tab character \tab Unique official / referee identifier. \cr
#'    display_name \tab character \tab Display name. \cr
#'    full_name \tab character \tab Player's full name. \cr
#'    first_name \tab character \tab Player's first name. \cr
#'    last_name \tab character \tab Player's last name. \cr
#'    position \tab character \tab Listed roster position (G, F, C, etc.). \cr
#'    order \tab integer \tab Display order within the result set. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name basketball_load_wbb_officials_schema
#' @keywords internal
NULL

#' Shared column schema: basketball load wbb shots schema
#'
#' Columns shared verbatim across: load_wbb_shots, load_wnba_shots.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    game_id \tab character \tab Unique game identifier. \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    period_number \tab integer \tab Numeric period (1-4 for quarters; 5+ for OT). \cr
#'    clock_display_value \tab character \tab Game clock display string (e.g. '8:32'). \cr
#'    team_id \tab character \tab Unique team identifier. \cr
#'    athlete_id_1 \tab character \tab Primary athlete identifier (e.g. shooter). \cr
#'    athlete_id_2 \tab character \tab Secondary athlete identifier (e.g. assister / fouler). \cr
#'    type_id \tab character \tab Type identifier (numeric). \cr
#'    type_text \tab character \tab Display text for the type field. \cr
#'    scoring_play \tab logical \tab TRUE if the play resulted in points scored. \cr
#'    score_value \tab integer \tab Point value of the play (2 / 3 / 1). \cr
#'    coordinate_x \tab numeric \tab X coordinate on the court (half-court layout). \cr
#'    coordinate_y \tab numeric \tab Y coordinate on the court (half-court layout). \cr
#'    coordinate_x_raw \tab numeric \tab X coordinate as returned by the API before any adjustment. \cr
#'    coordinate_y_raw \tab numeric \tab Y coordinate as returned by the API before any adjustment. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name basketball_load_wbb_shots_schema
#' @keywords internal
NULL

#' Shared column schema: basketball load wbb standings schema
#'
#' Columns shared verbatim across: load_wbb_standings, load_wnba_standings.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    season_type \tab integer \tab Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). \cr
#'    team_id \tab character \tab Unique team identifier. \cr
#'    team_slug \tab character \tab URL-safe team identifier (e.g. 'lasvegas-aces' / 'aces'). \cr
#'    team_location \tab character \tab Team city or location string. \cr
#'    team_name \tab character \tab Full team display name (e.g. 'Las Vegas Aces'). \cr
#'    team_abbreviation \tab character \tab Short team abbreviation (e.g. 'LAS'). \cr
#'    team_display_name \tab character \tab Full team display name. \cr
#'    conference_id \tab character \tab Conference identifier. \cr
#'    conference_name \tab character \tab Full conference name. \cr
#'    wins \tab integer \tab Total wins. \cr
#'    losses \tab integer \tab Total losses. \cr
#'    win_percent \tab numeric \tab Win percent. \cr
#'    games_played \tab integer \tab Games played. \cr
#'    points_for \tab numeric \tab Points for. \cr
#'    points_against \tab numeric \tab Points allowed. \cr
#'    point_differential \tab numeric \tab Point differential. \cr
#'    streak \tab character \tab Current streak (e.g. 'W3' for three-game win streak). \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name basketball_load_wbb_standings_schema
#' @keywords internal
NULL

#' Shared column schema: basketball load wbb team stats schema
#'
#' Columns shared verbatim across: load_wbb_team_stats, load_wnba_team_stats.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    season_type \tab integer \tab Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). \cr
#'    team_id \tab character \tab Unique team identifier. \cr
#'    team_slug \tab character \tab URL-safe team identifier (e.g. 'lasvegas-aces' / 'aces'). \cr
#'    team_location \tab character \tab Team city or location string. \cr
#'    team_name \tab character \tab Full team display name (e.g. 'Las Vegas Aces'). \cr
#'    team_abbreviation \tab character \tab Short team abbreviation (e.g. 'LAS'). \cr
#'    team_display_name \tab character \tab Full team display name. \cr
#'    category \tab character \tab Category label. \cr
#'    stat_name \tab character \tab Stat name. \cr
#'    stat_display_name \tab character \tab Stat display name. \cr
#'    stat_value \tab numeric \tab Stat value. \cr
#'    stat_display_value \tab character \tab Stat display value. \cr
#'    stat_rank \tab integer \tab League/season rank for stat. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name basketball_load_wbb_team_stats_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball athletes index schema
#'
#' Columns shared verbatim across: espn_wbb_athletes_index, espn_wnba_athletes_index.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    athlete_id \tab character \tab Unique athlete identifier (ESPN). \cr
#'    full_name \tab character \tab Player's full name. \cr
#'    jersey \tab character \tab Jersey number worn by the player. \cr
#'    position \tab character \tab Listed roster position (G, F, C, etc.). \cr
#'    team_id \tab character \tab Unique team identifier. \cr
#'    headshot \tab character \tab Headshot image URL. \cr
#'    status \tab character \tab Status label. \cr
#'    link \tab character \tab Link. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_athletes_index_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball calendar schema
#'
#' Columns shared verbatim across: espn_wbb_calendar, espn_wnba_calendar.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    season \tab character \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    season_type \tab character \tab Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). \cr
#'    season_type_label \tab character \tab Season type label. \cr
#'    season_start_date \tab character \tab Date in YYYY-MM-DD format. \cr
#'    season_end_date \tab character \tab Date in YYYY-MM-DD format. \cr
#'    label \tab character \tab Label. \cr
#'    alternate_label \tab character \tab Alternate label. \cr
#'    detail \tab character \tab Detail. \cr
#'    value \tab character \tab Numeric or string value field. \cr
#'    start_date \tab character \tab Start date (YYYY-MM-DD). \cr
#'    end_date \tab character \tab End date (YYYY-MM-DD). \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_calendar_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball coach season schema
#'
#' Columns shared verbatim across: espn_wbb_coach_season, espn_wnba_coach_season.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    league \tab character \tab League slug. \cr
#'    season \tab integer \tab Season year. \cr
#'    coach_id \tab character \tab ESPN coach id. \cr
#'    uid \tab character \tab ESPN UID string. \cr
#'    first_name \tab character \tab First name. \cr
#'    last_name \tab character \tab Last name. \cr
#'    date_of_birth \tab character \tab Date of birth. \cr
#'    birth_city \tab character \tab Birth city. \cr
#'    birth_state \tab character \tab Birth state / region. \cr
#'    n_records \tab integer \tab Count of records entries. \cr
#'    person_ref \tab character \tab \verb{$ref} to person resource. \cr
#'    college_ref \tab character \tab \verb{$ref} to college. \cr
#'    team_ref \tab character \tab \verb{$ref} to team-in-season. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_coach_season_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball conferences schema
#'
#' Columns shared verbatim across: espn_wbb_conferences, espn_wnba_conferences.
#'
#' |col_name |types |description |
#' |:---------------------|:---------|:--------------------------------------------|
#' |group_id |integer |Group identifier (e.g. conference group_id). |
#' |conference_short_name |character |Conference short name (e.g. 'ACC'). |
#' |conference_uid |character |ESPN universal conference identifier. |
#' |conference_name |character |Full conference name. |
#' |conference_logo |character |Logo image URL for conference. |
#' |parent_group_id |integer |Unique identifier for parent group. |
#' |conference_id |integer |Conference identifier. |
#'
#' @name espn_basketball_conferences_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game all player player schema
#'
#' Columns shared verbatim across: espn_wbb_game_all, espn_wbb_player_box.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    game_id \tab integer \tab Unique game identifier. \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    season_type \tab integer \tab Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). \cr
#'    game_date \tab Date \tab Game date (YYYY-MM-DD). \cr
#'    game_date_time \tab POSIXct \tab Game start date/time (ISO 8601). \cr
#'    athlete_id \tab integer \tab Unique athlete identifier (ESPN). \cr
#'    athlete_display_name \tab character \tab Athlete display name (full). \cr
#'    team_id \tab integer \tab Unique team identifier. \cr
#'    team_name \tab character \tab Full team display name (e.g. 'Las Vegas Aces'). \cr
#'    team_location \tab character \tab Team city or location string. \cr
#'    team_short_display_name \tab character \tab Short team display name (e.g. 'Aces'). \cr
#'    minutes \tab numeric \tab Minutes played, formatted MM:SS (V3 PT-duration parsed) or decimal minutes (V2). \cr
#'    field_goals_made \tab integer \tab Field goals made (2-pt + 3-pt). \cr
#'    field_goals_attempted \tab integer \tab Field goal attempts (2-pt + 3-pt). \cr
#'    three_point_field_goals_made \tab integer \tab Three-point field goals made. \cr
#'    three_point_field_goals_attempted \tab integer \tab Three-point field goal attempts. \cr
#'    free_throws_made \tab integer \tab Free throws made. \cr
#'    free_throws_attempted \tab integer \tab Free throw attempts. \cr
#'    offensive_rebounds \tab integer \tab Offensive rebounds. \cr
#'    defensive_rebounds \tab integer \tab Defensive rebounds. \cr
#'    rebounds \tab integer \tab Total rebounds. \cr
#'    assists \tab integer \tab Total assists. \cr
#'    steals \tab integer \tab Total steals. \cr
#'    blocks \tab integer \tab Total blocks. \cr
#'    turnovers \tab integer \tab Total turnovers. \cr
#'    fouls \tab integer \tab Personal fouls. \cr
#'    points \tab integer \tab Points scored. \cr
#'    starter \tab logical \tab TRUE if the player was in the starting lineup; FALSE otherwise. \cr
#'    ejected \tab logical \tab TRUE if the player was ejected from the game. \cr
#'    did_not_play \tab logical \tab TRUE if the player did not appear in the game. \cr
#'    active \tab logical \tab TRUE if the row represents an active record (player / team / season). \cr
#'    athlete_jersey \tab character \tab Athlete jersey number. \cr
#'    athlete_short_name \tab character \tab Athlete short display name. \cr
#'    athlete_headshot_href \tab character \tab Athlete headshot image URL. \cr
#'    athlete_position_name \tab character \tab Athlete position ('Guard', 'Forward', 'Center'). \cr
#'    athlete_position_abbreviation \tab character \tab Athlete position abbreviation (G / F / C). \cr
#'    team_display_name \tab character \tab Full team display name. \cr
#'    team_uid \tab character \tab ESPN universal team identifier (UID format 's:40~l:...~t:...'). \cr
#'    team_slug \tab character \tab URL-safe team identifier (e.g. 'lasvegas-aces' / 'aces'). \cr
#'    team_logo \tab character \tab Team logo image URL. \cr
#'    team_abbreviation \tab character \tab Short team abbreviation (e.g. 'LAS'). \cr
#'    team_color \tab character \tab Team primary color (hex without leading '#'). \cr
#'    team_alternate_color \tab character \tab Team alternate color (hex without leading '#'). \cr
#'    home_away \tab character \tab Game venue label ('home' or 'away'). \cr
#'    team_winner \tab logical \tab TRUE if the team won this game. \cr
#'    team_score \tab integer \tab Team's score / final score. \cr
#'    opponent_team_id \tab integer \tab Unique identifier for the opponent team. \cr
#'    opponent_team_name \tab character \tab Opponent team display name. \cr
#'    opponent_team_location \tab character \tab Opponent team city / location. \cr
#'    opponent_team_display_name \tab character \tab Opponent team full display name. \cr
#'    opponent_team_abbreviation \tab character \tab Opponent team abbreviation. \cr
#'    opponent_team_logo \tab character \tab Opponent team logo URL. \cr
#'    opponent_team_color \tab character \tab Opponent team primary color (hex). \cr
#'    opponent_team_alternate_color \tab character \tab Opponent team alternate color (hex). \cr
#'    opponent_team_score \tab integer \tab Opponent team's score. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_game_all_player_player_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game all player schema
#'
#' Columns shared verbatim across: espn_wnba_game_all, espn_wnba_player_box.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    game_id \tab integer \tab Unique game identifier. \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    season_type \tab integer \tab Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). \cr
#'    game_date \tab Date \tab Game date (YYYY-MM-DD). \cr
#'    game_date_time \tab POSIXct \tab Game start date/time (ISO 8601). \cr
#'    athlete_id \tab integer \tab Unique athlete identifier (ESPN). \cr
#'    athlete_display_name \tab character \tab Athlete display name (full). \cr
#'    team_id \tab integer \tab Unique team identifier. \cr
#'    team_name \tab character \tab Full team display name (e.g. 'Las Vegas Aces'). \cr
#'    team_location \tab character \tab Team city or location string. \cr
#'    team_short_display_name \tab character \tab Short team display name (e.g. 'Aces'). \cr
#'    minutes \tab numeric \tab Minutes played, formatted MM:SS (V3 PT-duration parsed) or decimal minutes (V2). \cr
#'    field_goals_made \tab integer \tab Field goals made (2-pt + 3-pt). \cr
#'    field_goals_attempted \tab integer \tab Field goal attempts (2-pt + 3-pt). \cr
#'    three_point_field_goals_made \tab integer \tab Three-point field goals made. \cr
#'    three_point_field_goals_attempted \tab integer \tab Three-point field goal attempts. \cr
#'    free_throws_made \tab integer \tab Free throws made. \cr
#'    free_throws_attempted \tab integer \tab Free throw attempts. \cr
#'    offensive_rebounds \tab integer \tab Offensive rebounds. \cr
#'    defensive_rebounds \tab integer \tab Defensive rebounds. \cr
#'    rebounds \tab integer \tab Total rebounds. \cr
#'    assists \tab integer \tab Total assists. \cr
#'    steals \tab integer \tab Total steals. \cr
#'    blocks \tab integer \tab Total blocks. \cr
#'    turnovers \tab integer \tab Total turnovers. \cr
#'    fouls \tab integer \tab Personal fouls. \cr
#'    plus_minus \tab character \tab Plus/minus point differential while on court. \cr
#'    points \tab integer \tab Points scored. \cr
#'    starter \tab logical \tab TRUE if the player was in the starting lineup; FALSE otherwise. \cr
#'    ejected \tab logical \tab TRUE if the player was ejected from the game. \cr
#'    did_not_play \tab logical \tab TRUE if the player did not appear in the game. \cr
#'    reason \tab character \tab Reason. \cr
#'    active \tab logical \tab TRUE if the row represents an active record (player / team / season). \cr
#'    athlete_jersey \tab character \tab Athlete jersey number. \cr
#'    athlete_short_name \tab character \tab Athlete short display name. \cr
#'    athlete_headshot_href \tab character \tab Athlete headshot image URL. \cr
#'    athlete_position_name \tab character \tab Athlete position ('Guard', 'Forward', 'Center'). \cr
#'    athlete_position_abbreviation \tab character \tab Athlete position abbreviation (G / F / C). \cr
#'    team_display_name \tab character \tab Full team display name. \cr
#'    team_uid \tab character \tab ESPN universal team identifier (UID format 's:40~l:...~t:...'). \cr
#'    team_slug \tab character \tab URL-safe team identifier (e.g. 'lasvegas-aces' / 'aces'). \cr
#'    team_logo \tab character \tab Team logo image URL. \cr
#'    team_abbreviation \tab character \tab Short team abbreviation (e.g. 'LAS'). \cr
#'    team_color \tab character \tab Team primary color (hex without leading '#'). \cr
#'    team_alternate_color \tab character \tab Team alternate color (hex without leading '#'). \cr
#'    home_away \tab character \tab Game venue label ('home' or 'away'). \cr
#'    team_winner \tab logical \tab TRUE if the team won this game. \cr
#'    team_score \tab integer \tab Team's score / final score. \cr
#'    opponent_team_id \tab integer \tab Unique identifier for the opponent team. \cr
#'    opponent_team_name \tab character \tab Opponent team display name. \cr
#'    opponent_team_location \tab character \tab Opponent team city / location. \cr
#'    opponent_team_display_name \tab character \tab Opponent team full display name. \cr
#'    opponent_team_abbreviation \tab character \tab Opponent team abbreviation. \cr
#'    opponent_team_logo \tab character \tab Opponent team logo URL. \cr
#'    opponent_team_color \tab character \tab Opponent team primary color (hex). \cr
#'    opponent_team_alternate_color \tab character \tab Opponent team alternate color (hex). \cr
#'    opponent_team_score \tab integer \tab Opponent team's score. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_game_all_player_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game all plays plays schema
#'
#' Columns shared verbatim across: espn_wbb_game_all, espn_wbb_pbp.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    id \tab character \tab Unique play identifcation number \cr
#'    sequence_number \tab character \tab Sequence number representing a shot-possession (V3 PBP). \cr
#'    text \tab character \tab Text description of the play / record. \cr
#'    away_score \tab integer \tab Away team score at the time of the play. \cr
#'    home_score \tab integer \tab Home team score at the time of the play. \cr
#'    scoring_play \tab logical \tab TRUE if the play resulted in points scored. \cr
#'    score_value \tab integer \tab Point value of the play (2 / 3 / 1). \cr
#'    wallclock \tab character \tab Wallclock. \cr
#'    shooting_play \tab logical \tab TRUE if the play was a shooting attempt. \cr
#'    type_id \tab integer \tab Type identifier (numeric). \cr
#'    type_text \tab character \tab Display text for the type field. \cr
#'    period_number \tab integer \tab Numeric period (1-4 for quarters; 5+ for OT). \cr
#'    period_display_value \tab character \tab Period display label (e.g. '1st Quarter', 'OT'). \cr
#'    clock_display_value \tab character \tab Game clock display string (e.g. '8:32'). \cr
#'    team_id \tab integer \tab Unique team identifier. \cr
#'    coordinate_x_raw \tab numeric \tab X coordinate as returned by the API before any adjustment. \cr
#'    coordinate_y_raw \tab numeric \tab Y coordinate as returned by the API before any adjustment. \cr
#'    coordinate_x \tab numeric \tab X coordinate on the court (half-court layout). \cr
#'    coordinate_y \tab numeric \tab Y coordinate on the court (half-court layout). \cr
#'    play_id \tab character \tab Unique play identifier within a game. \cr
#'    athlete_id_1 \tab integer \tab Primary athlete identifier (e.g. shooter). \cr
#'    athlete_id_2 \tab integer \tab Secondary athlete identifier (e.g. assister / fouler). \cr
#'    home_team_id \tab integer \tab Unique identifier for the home team. \cr
#'    home_team_mascot \tab character \tab Home team mascot. \cr
#'    home_team_name \tab character \tab Home team name. \cr
#'    home_team_abbrev \tab character \tab Home team three-letter abbreviation. \cr
#'    home_team_logo \tab character \tab Home team logo URL. \cr
#'    home_team_logo_dark \tab character \tab Home team logo URL for dark backgrounds. \cr
#'    home_team_full_name \tab character \tab Full home team name (e.g. 'Las Vegas Aces'). \cr
#'    home_team_color \tab character \tab Home team primary color (hex). \cr
#'    home_team_alternate_color \tab character \tab Home team alternate color (hex). \cr
#'    home_team_score \tab integer \tab Home team's score. \cr
#'    home_team_winner \tab logical \tab TRUE if the home team won this game. \cr
#'    home_team_record \tab character \tab Home team's win-loss record. \cr
#'    away_team_id \tab integer \tab Unique identifier for the away team. \cr
#'    away_team_mascot \tab character \tab Away team mascot. \cr
#'    away_team_name \tab character \tab Away team name. \cr
#'    away_team_abbrev \tab character \tab Away team three-letter abbreviation. \cr
#'    away_team_logo \tab character \tab Away team logo URL. \cr
#'    away_team_logo_dark \tab character \tab Away team logo URL for dark backgrounds. \cr
#'    away_team_full_name \tab character \tab Full away team name (e.g. 'Las Vegas Aces'). \cr
#'    away_team_color \tab character \tab Away team primary color (hex). \cr
#'    away_team_alternate_color \tab character \tab Away team alternate color (hex). \cr
#'    away_team_score \tab integer \tab Away team's score. \cr
#'    away_team_winner \tab logical \tab TRUE if the away team won this game. \cr
#'    away_team_record \tab character \tab Away team's win-loss record. \cr
#'    game_id \tab integer \tab Unique game identifier. \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    season_type \tab integer \tab Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). \cr
#'    game_date \tab Date \tab Game date (YYYY-MM-DD). \cr
#'    game_date_time \tab POSIXct \tab Game start date/time (ISO 8601). \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_game_all_plays_plays_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game all plays schema
#'
#' Columns shared verbatim across: espn_wnba_game_all, espn_wnba_pbp.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    id \tab character \tab Unique play identifcation number \cr
#'    sequence_number \tab character \tab Sequence number representing a shot-possession (V3 PBP). \cr
#'    text \tab character \tab Text description of the play / record. \cr
#'    away_score \tab integer \tab Away team score at the time of the play. \cr
#'    home_score \tab integer \tab Home team score at the time of the play. \cr
#'    scoring_play \tab logical \tab TRUE if the play resulted in points scored. \cr
#'    score_value \tab integer \tab Point value of the play (2 / 3 / 1). \cr
#'    wallclock \tab character \tab Wallclock. \cr
#'    shooting_play \tab logical \tab TRUE if the play was a shooting attempt. \cr
#'    type_id \tab integer \tab Type identifier (numeric). \cr
#'    type_text \tab character \tab Display text for the type field. \cr
#'    period_number \tab integer \tab Numeric period (1-4 for quarters; 5+ for OT). \cr
#'    period_display_value \tab character \tab Period display label (e.g. '1st Quarter', 'OT'). \cr
#'    clock_display_value \tab character \tab Game clock display string (e.g. '8:32'). \cr
#'    team_id \tab integer \tab Unique team identifier. \cr
#'    coordinate_x_raw \tab numeric \tab X coordinate as returned by the API before any adjustment. \cr
#'    coordinate_y_raw \tab numeric \tab Y coordinate as returned by the API before any adjustment. \cr
#'    coordinate_x \tab numeric \tab X coordinate on the court (half-court layout). \cr
#'    coordinate_y \tab numeric \tab Y coordinate on the court (half-court layout). \cr
#'    play_id \tab character \tab Unique play identifier within a game. \cr
#'    athlete_id_1 \tab integer \tab Primary athlete identifier (e.g. shooter). \cr
#'    athlete_id_2 \tab integer \tab Secondary athlete identifier (e.g. assister / fouler). \cr
#'    athlete_id_3 \tab integer \tab Athlete id 3. \cr
#'    home_team_id \tab integer \tab Unique identifier for the home team. \cr
#'    home_team_mascot \tab character \tab Home team mascot. \cr
#'    home_team_name \tab character \tab Home team name. \cr
#'    home_team_abbrev \tab character \tab Home team three-letter abbreviation. \cr
#'    home_team_logo \tab character \tab Home team logo URL. \cr
#'    home_team_logo_dark \tab character \tab Home team logo URL for dark backgrounds. \cr
#'    home_team_full_name \tab character \tab Full home team name (e.g. 'Las Vegas Aces'). \cr
#'    home_team_color \tab character \tab Home team primary color (hex). \cr
#'    home_team_alternate_color \tab character \tab Home team alternate color (hex). \cr
#'    home_team_score \tab integer \tab Home team's score. \cr
#'    home_team_winner \tab logical \tab TRUE if the home team won this game. \cr
#'    home_team_record \tab character \tab Home team's win-loss record. \cr
#'    away_team_id \tab integer \tab Unique identifier for the away team. \cr
#'    away_team_mascot \tab character \tab Away team mascot. \cr
#'    away_team_name \tab character \tab Away team name. \cr
#'    away_team_abbrev \tab character \tab Away team three-letter abbreviation. \cr
#'    away_team_logo \tab character \tab Away team logo URL. \cr
#'    away_team_logo_dark \tab character \tab Away team logo URL for dark backgrounds. \cr
#'    away_team_full_name \tab character \tab Full away team name (e.g. 'Las Vegas Aces'). \cr
#'    away_team_color \tab character \tab Away team primary color (hex). \cr
#'    away_team_alternate_color \tab character \tab Away team alternate color (hex). \cr
#'    away_team_score \tab integer \tab Away team's score. \cr
#'    away_team_winner \tab logical \tab TRUE if the away team won this game. \cr
#'    away_team_record \tab character \tab Away team's win-loss record. \cr
#'    game_id \tab integer \tab Unique game identifier. \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    season_type \tab integer \tab Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). \cr
#'    game_date \tab Date \tab Game date (YYYY-MM-DD). \cr
#'    game_date_time \tab POSIXct \tab Game start date/time (ISO 8601). \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_game_all_plays_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game broadcasts schema
#'
#' Columns shared verbatim across: espn_wbb_game_broadcasts, espn_wnba_game_broadcasts.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    event_id \tab character \tab Unique event / game identifier (ESPN). \cr
#'    broadcast_id \tab character \tab Unique identifier for broadcast. \cr
#'    type_id \tab character \tab Type identifier (numeric). \cr
#'    type_short_name \tab character \tab Type short name. \cr
#'    type_long_name \tab character \tab Type long name. \cr
#'    market_id \tab character \tab Unique identifier for market. \cr
#'    market_type \tab character \tab Market type. \cr
#'    names \tab character \tab Names. \cr
#'    lang \tab character \tab Lang. \cr
#'    region \tab character \tab Region label. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_game_broadcasts_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game odds schema
#'
#' Columns shared verbatim across: espn_wbb_game_odds, espn_wnba_game_odds.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    event_id \tab character \tab Unique event / game identifier (ESPN). \cr
#'    provider_id \tab character \tab Unique identifier for provider. \cr
#'    provider_name \tab character \tab Provider name. \cr
#'    details \tab character \tab Details. \cr
#'    over_under \tab numeric \tab Over under. \cr
#'    spread \tab numeric \tab Spread. \cr
#'    home_money_line \tab integer \tab Home team's money line. \cr
#'    away_money_line \tab integer \tab Away team's money line. \cr
#'    home_team_odds_open \tab numeric \tab Home team's team odds open. \cr
#'    home_team_odds_close \tab numeric \tab Home team's team odds close. \cr
#'    away_team_odds_open \tab numeric \tab Away team's team odds open. \cr
#'    away_team_odds_close \tab numeric \tab Away team's team odds close. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_game_odds_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game officials schema
#'
#' Columns shared verbatim across: espn_wbb_game_officials, espn_wnba_game_officials.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    event_id \tab character \tab Unique event / game identifier (ESPN). \cr
#'    official_id \tab character \tab Unique official / referee identifier. \cr
#'    full_name \tab character \tab Player's full name. \cr
#'    display_name \tab character \tab Display name. \cr
#'    position_id \tab character \tab Unique position identifier. \cr
#'    position_name \tab character \tab Listed roster position ('Guard', 'Forward', 'Center'). \cr
#'    position_type \tab character \tab Position type. \cr
#'    order \tab integer \tab Display order within the result set. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_game_officials_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game probabilities schema
#'
#' Columns shared verbatim across: espn_wbb_game_probabilities, espn_wnba_game_probabilities.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    event_id \tab character \tab Unique event / game identifier (ESPN). \cr
#'    sequence_number \tab character \tab Sequence number representing a shot-possession (V3 PBP). \cr
#'    play_id \tab character \tab Unique play identifier within a game. \cr
#'    period \tab integer \tab Period of the game (1-4 quarters; 5+ for OT). \cr
#'    clock \tab character \tab Game clock value. \cr
#'    home_win_percentage \tab numeric \tab Home win percentage (0-1 decimal). \cr
#'    away_win_percentage \tab numeric \tab Away win percentage (0-1 decimal). \cr
#'    tie_percentage \tab numeric \tab Tie percentage (0-1 decimal). \cr
#'    secs_to_end_of_period \tab numeric \tab Secs to end of period. \cr
#'    secs_to_end_of_game \tab numeric \tab Secs to end of game. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_game_probabilities_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball injuries schema
#'
#' Columns shared verbatim across: espn_wbb_injuries, espn_wnba_injuries.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    team_id \tab character \tab Unique team identifier. \cr
#'    athlete_id \tab character \tab Unique athlete identifier (ESPN). \cr
#'    athlete_name \tab character \tab Athlete display name (ESPN). \cr
#'    position \tab character \tab Listed roster position (G, F, C, etc.). \cr
#'    status \tab character \tab Status label. \cr
#'    date \tab character \tab Date in YYYY-MM-DD format. \cr
#'    type \tab character \tab Record type / category. \cr
#'    side \tab character \tab Side label (e.g. 'home', 'away', or 'overUnder'). \cr
#'    returns_at \tab character \tab Returns at. \cr
#'    short_comment \tab character \tab Short comment. \cr
#'    long_comment \tab character \tab Long-form play / event comment. \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_injuries_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball leaders schema
#'
#' Columns shared verbatim across: espn_wbb_leaders, espn_wnba_leaders.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    season_type \tab integer \tab Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). \cr
#'    category \tab character \tab Category label. \cr
#'    abbreviation \tab character \tab Short abbreviation. \cr
#'    athlete_id \tab character \tab Unique athlete identifier (ESPN). \cr
#'    athlete_name \tab character \tab Athlete display name (ESPN). \cr
#'    team_id \tab character \tab Unique team identifier. \cr
#'    team_abbrev \tab character \tab Abbreviation for team. \cr
#'    value \tab numeric \tab Numeric or string value field. \cr
#'    rank \tab integer \tab Whether to include statistical ranks in the returned table. \cr
#'    display_value \tab character \tab Human-readable display value. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_leaders_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball news schema
#'
#' Columns shared verbatim across: espn_wbb_news, espn_wbb_team_news, espn_wnba_news, espn_wnba_team_news.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    id \tab character \tab Unique play identifcation number \cr
#'    type \tab character \tab Record type / category. \cr
#'    headline \tab character \tab News headline. \cr
#'    description \tab character \tab Long-form description text. \cr
#'    published \tab character \tab Publication timestamp (ISO 8601). \cr
#'    premium \tab logical \tab Premium. \cr
#'    byline \tab character \tab News article byline / author. \cr
#'    link_web \tab character \tab Web link / URL. \cr
#'    league_id \tab character \tab League identifier ('10' = WNBA). \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_news_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball player awards schema
#'
#' Columns shared verbatim across: espn_wbb_player_awards, espn_wnba_player_awards.
#'
#' |col_name |types |description |
#' |:-----------|:---------|:-----------------------------------------------------|
#' |season |character |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |award_id |character |Unique identifier for award. |
#' |name |character |Display name. |
#' |description |character |Long-form description text. |
#' |date |character |Date in YYYY-MM-DD format. |
#' |type |character |Record type / category. |
#'
#' @name espn_basketball_player_awards_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball player career stats schema
#'
#' Columns shared verbatim across: espn_wbb_player_career_stats, espn_wnba_player_career_stats.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    league \tab character \tab League slug. \cr
#'    athlete_id \tab character \tab ESPN athlete id. \cr
#'    stat_type_id \tab character \tab Stat-type code (0 = reg, 1 = post, 2 = career). \cr
#'    split_id \tab character \tab Split id. \cr
#'    split_name \tab character \tab Split name (typically "All Splits"). \cr
#'    split_type \tab character \tab Split type code. \cr
#'    category_name \tab character \tab Category key (e.g. "defensive"). \cr
#'    category_display \tab character \tab Category display name. \cr
#'    category_short \tab character \tab Category short display. \cr
#'    category_abbrev \tab character \tab Category abbreviation. \cr
#'    stat_name \tab character \tab Stat key. \cr
#'    stat_abbrev \tab character \tab Stat abbreviation. \cr
#'    stat_display \tab character \tab Stat display name. \cr
#'    stat_short \tab character \tab Stat short display. \cr
#'    description \tab character \tab Stat description. \cr
#'    value \tab numeric \tab Stat value. \cr
#'    display_value \tab character \tab Display-formatted value. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_player_career_stats_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball player info bio schema
#'
#' Columns shared verbatim across: espn_wbb_player_info, espn_wnba_player_info.
#'
#' |col_name |types |description |
#' |:-------------|:---------|:---------------------------------|
#' |id |character |Unique play identifcation number |
#' |full_name |character |Player's full name. |
#' |display_name |character |Display name. |
#' |jersey |character |Jersey number worn by the player. |
#' |age |character |Player age (in years). |
#' |date_of_birth |character |Date of birth (YYYY-MM-DD). |
#' |headshot_href |character |Headshot image URL. |
#'
#' @name espn_basketball_player_info_bio_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball player overview next game schema
#'
#' Columns shared verbatim across: espn_wbb_player_overview, espn_wbb_team, espn_wnba_player_overview, espn_wnba_team.
#'
#' |col_name |types |description |
#' |:----------|:---------|:--------------------------------|
#' |id |character |Unique play identifcation number |
#' |date |character |Date in YYYY-MM-DD format. |
#' |name |character |Display name. |
#' |short_name |character |Short display name. |
#'
#' @name espn_basketball_player_overview_next_game_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball player overview statistics schema
#'
#' Columns shared verbatim across: espn_wbb_player_overview, espn_wnba_player_overview.
#'
#' |col_name |types |description |
#' |:--------|:---------|:-----------|
#' |(varies) |character | |
#'
#' @name espn_basketball_player_overview_statistics_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball scoreboard schema
#'
#' Columns shared verbatim across: espn_wbb_scoreboard, espn_wnba_scoreboard.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    matchup \tab character \tab Matchup. \cr
#'    matchup_short \tab character \tab Matchup short. \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    season_type \tab integer \tab Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). \cr
#'    season_slug \tab character \tab Season slug. \cr
#'    game_id \tab integer \tab Unique game identifier. \cr
#'    game_uid \tab character \tab Game uid. \cr
#'    game_date \tab Date \tab Game date (YYYY-MM-DD). \cr
#'    attendance \tab integer \tab Reported attendance. \cr
#'    status_name \tab character \tab Status label. \cr
#'    broadcast_market \tab character \tab Broadcast market label (e.g. 'national', 'home'). \cr
#'    broadcast_name \tab character \tab Broadcast name. \cr
#'    start_date \tab character \tab Start date (YYYY-MM-DD). \cr
#'    game_date_time \tab POSIXct \tab Game start date/time (ISO 8601). \cr
#'    home_team_name \tab character \tab Home team name. \cr
#'    home_team_logo \tab character \tab Home team logo URL. \cr
#'    home_team_abb \tab character \tab Home team's team abb. \cr
#'    home_team_id \tab integer \tab Unique identifier for the home team. \cr
#'    home_team_location \tab character \tab Home team's team location. \cr
#'    home_team_full_name \tab character \tab Full home team name (e.g. 'Las Vegas Aces'). \cr
#'    home_team_color \tab character \tab Home team primary color (hex). \cr
#'    home_score \tab integer \tab Home team score at the time of the play. \cr
#'    home_win \tab integer \tab Home team's win. \cr
#'    home_record \tab character \tab Home win-loss record. \cr
#'    away_team_name \tab character \tab Away team name. \cr
#'    away_team_logo \tab character \tab Away team logo URL. \cr
#'    away_team_abb \tab character \tab Away team's team abb. \cr
#'    away_team_id \tab integer \tab Unique identifier for the away team. \cr
#'    away_team_location \tab character \tab Away team's team location. \cr
#'    away_team_full_name \tab character \tab Full away team name (e.g. 'Las Vegas Aces'). \cr
#'    away_team_color \tab character \tab Away team primary color (hex). \cr
#'    away_score \tab integer \tab Away team score at the time of the play. \cr
#'    away_win \tab integer \tab Away team's win. \cr
#'    away_record \tab character \tab Away win-loss record. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_scoreboard_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball season group schema
#'
#' Columns shared verbatim across: espn_wbb_season_group, espn_wnba_season_group.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    league \tab character \tab League slug. \cr
#'    season \tab integer \tab Season year. \cr
#'    season_type \tab integer \tab Season-type id. \cr
#'    group_id \tab character \tab ESPN group id. \cr
#'    uid \tab character \tab ESPN UID string. \cr
#'    name \tab character \tab Full name (e.g. "Eastern Conference"). \cr
#'    abbreviation \tab character \tab Short code (e.g. "EAST"). \cr
#'    short_name \tab character \tab Short name. \cr
#'    midsize_name \tab character \tab Mid-size display name. \cr
#'    is_conference \tab logical \tab Whether this group is a conference. \cr
#'    slug \tab character \tab URL slug. \cr
#'    parent_ref \tab character \tab \verb{$ref} to parent group (if any). \cr
#'    children_ref \tab character \tab \verb{$ref} to child-groups endpoint. \cr
#'    teams_ref \tab character \tab \verb{$ref} to teams-in-group endpoint. \cr
#'    standings_ref \tab character \tab \verb{$ref} to standings endpoint. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_season_group_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball season leaders schema
#'
#' Columns shared verbatim across: espn_wbb_season_leaders, espn_wnba_season_leaders.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    league \tab character \tab League slug. \cr
#'    season \tab integer \tab Season year. \cr
#'    season_type \tab integer \tab Season-type id. \cr
#'    category_name \tab character \tab Internal category key (e.g. "pointsPerGame"). \cr
#'    category_display \tab character \tab Human-readable category name. \cr
#'    category_short \tab character \tab Short display name. \cr
#'    category_abbrev \tab character \tab Stat abbreviation (e.g. "PTS"). \cr
#'    rank \tab integer \tab Rank within the category (1 = best). \cr
#'    athlete_id \tab character \tab ESPN athlete id. \cr
#'    team_id \tab character \tab ESPN team id. \cr
#'    display_value \tab character \tab Display-formatted value. \cr
#'    value \tab numeric \tab Numeric leader value. \cr
#'    rel \tab character \tab Comma-joined \code{rel} tags from ESPN. \cr
#'    athlete_ref \tab character \tab \verb{$ref} URL to the leader's athlete. \cr
#'    team_ref \tab character \tab \verb{$ref} URL to the leader's team. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_season_leaders_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball season ranking schema
#'
#' Columns shared verbatim across: espn_wbb_season_ranking, espn_wnba_season_ranking.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    league \tab character \tab League slug. \cr
#'    season \tab integer \tab Season year. \cr
#'    ranking_id \tab character \tab ESPN ranking id. \cr
#'    name \tab character \tab Ranking name (e.g. "AP Top 25"). \cr
#'    short_name \tab character \tab Short name (e.g. "AP Poll"). \cr
#'    type \tab character \tab Ranking type code (e.g. "ap"). \cr
#'    season_type \tab integer \tab Season-type id of this snapshot. \cr
#'    week \tab integer \tab Week number of this snapshot. \cr
#'    ref \tab character \tab \verb{$ref} URL for the per-week ranking detail. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_season_ranking_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball season type schema
#'
#' Columns shared verbatim across: espn_wbb_season_type, espn_wnba_season_type.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    league \tab character \tab League slug. \cr
#'    season \tab integer \tab Season year. \cr
#'    season_type \tab integer \tab Season-type id. \cr
#'    type \tab integer \tab Numeric type code. \cr
#'    name \tab character \tab Display name (e.g. "Regular Season"). \cr
#'    abbreviation \tab character \tab Short code (e.g. "reg"). \cr
#'    year \tab integer \tab Year stamp. \cr
#'    start_date \tab character \tab ISO 8601 start date. \cr
#'    end_date \tab character \tab ISO 8601 end date. \cr
#'    has_groups \tab logical \tab Whether groups exist for this type. \cr
#'    has_standings \tab logical \tab Whether standings exist. \cr
#'    has_legs \tab logical \tab Whether playoff legs exist. \cr
#'    slug \tab character \tab URL slug. \cr
#'    groups_ref \tab character \tab \verb{$ref} to the groups endpoint. \cr
#'    weeks_ref \tab character \tab \verb{$ref} to the weeks endpoint. \cr
#'    leaders_ref \tab character \tab \verb{$ref} to the leaders endpoint. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_season_type_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball season week schema
#'
#' Columns shared verbatim across: espn_wbb_season_week, espn_wnba_season_week.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    league \tab character \tab League slug. \cr
#'    season \tab integer \tab Season year. \cr
#'    season_type \tab integer \tab Season-type id. \cr
#'    week \tab integer \tab Week number. \cr
#'    text \tab character \tab Display label (e.g. "Week 5"). \cr
#'    start_date \tab character \tab ISO 8601 week start. \cr
#'    end_date \tab character \tab ISO 8601 week end. \cr
#'    rankings_ref \tab character \tab \verb{$ref} to the per-week rankings endpoint. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_season_week_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball team box schema
#'
#' Columns shared verbatim across: espn_wbb_game_all, espn_wbb_team_box, espn_wnba_game_all, espn_wnba_team_box.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    game_id \tab integer \tab Unique game identifier. \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    season_type \tab integer \tab Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). \cr
#'    game_date \tab Date \tab Game date (YYYY-MM-DD). \cr
#'    game_date_time \tab POSIXct \tab Game start date/time (ISO 8601). \cr
#'    team_id \tab integer \tab Unique team identifier. \cr
#'    team_uid \tab character \tab ESPN universal team identifier (UID format 's:40~l:...~t:...'). \cr
#'    team_slug \tab character \tab URL-safe team identifier (e.g. 'lasvegas-aces' / 'aces'). \cr
#'    team_location \tab character \tab Team city or location string. \cr
#'    team_name \tab character \tab Full team display name (e.g. 'Las Vegas Aces'). \cr
#'    team_abbreviation \tab character \tab Short team abbreviation (e.g. 'LAS'). \cr
#'    team_display_name \tab character \tab Full team display name. \cr
#'    team_short_display_name \tab character \tab Short team display name (e.g. 'Aces'). \cr
#'    team_color \tab character \tab Team primary color (hex without leading '#'). \cr
#'    team_alternate_color \tab character \tab Team alternate color (hex without leading '#'). \cr
#'    team_logo \tab character \tab Team logo image URL. \cr
#'    team_home_away \tab character \tab Team home away. \cr
#'    team_score \tab integer \tab Team's score / final score. \cr
#'    team_winner \tab logical \tab TRUE if the team won this game. \cr
#'    assists \tab integer \tab Total assists. \cr
#'    blocks \tab integer \tab Total blocks. \cr
#'    defensive_rebounds \tab integer \tab Defensive rebounds. \cr
#'    field_goal_pct \tab numeric \tab Field goal percentage (0-1). \cr
#'    field_goals_made \tab integer \tab Field goals made (2-pt + 3-pt). \cr
#'    field_goals_attempted \tab integer \tab Field goal attempts (2-pt + 3-pt). \cr
#'    flagrant_fouls \tab integer \tab Total flagrant fouls. \cr
#'    fouls \tab integer \tab Personal fouls. \cr
#'    free_throw_pct \tab numeric \tab Free throw percentage (0-1). \cr
#'    free_throws_made \tab integer \tab Free throws made. \cr
#'    free_throws_attempted \tab integer \tab Free throw attempts. \cr
#'    largest_lead \tab character \tab Largest lead during the game. \cr
#'    offensive_rebounds \tab integer \tab Offensive rebounds. \cr
#'    steals \tab integer \tab Total steals. \cr
#'    team_turnovers \tab integer \tab Team turnovers (turnovers credited to the team rather than a player). \cr
#'    technical_fouls \tab integer \tab Total technical fouls. \cr
#'    three_point_field_goal_pct \tab numeric \tab Three-point field goal percentage (0-1). \cr
#'    three_point_field_goals_made \tab integer \tab Three-point field goals made. \cr
#'    three_point_field_goals_attempted \tab integer \tab Three-point field goal attempts. \cr
#'    total_rebounds \tab integer \tab Total rebounds. \cr
#'    total_technical_fouls \tab integer \tab Total technical fouls (player + team). \cr
#'    total_turnovers \tab integer \tab Total turnovers (player + team). \cr
#'    turnovers \tab integer \tab Total turnovers. \cr
#'    opponent_team_id \tab integer \tab Unique identifier for the opponent team. \cr
#'    opponent_team_uid \tab character \tab Opponent team uid. \cr
#'    opponent_team_slug \tab character \tab Opponent team slug. \cr
#'    opponent_team_location \tab character \tab Opponent team city / location. \cr
#'    opponent_team_name \tab character \tab Opponent team display name. \cr
#'    opponent_team_abbreviation \tab character \tab Opponent team abbreviation. \cr
#'    opponent_team_display_name \tab character \tab Opponent team full display name. \cr
#'    opponent_team_short_display_name \tab character \tab Opponent team short display name. \cr
#'    opponent_team_color \tab character \tab Opponent team primary color (hex). \cr
#'    opponent_team_alternate_color \tab character \tab Opponent team alternate color (hex). \cr
#'    opponent_team_logo \tab character \tab Opponent team logo URL. \cr
#'    opponent_team_score \tab integer \tab Opponent team's score. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_team_box_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball team info schema
#'
#' Columns shared verbatim across: espn_wbb_team, espn_wnba_team.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    id \tab character \tab Unique play identifcation number \cr
#'    uid \tab character \tab ESPN UID string (universal identifier). \cr
#'    slug \tab character \tab URL-safe identifier. \cr
#'    abbreviation \tab character \tab Short abbreviation. \cr
#'    display_name \tab character \tab Display name. \cr
#'    short_display_name \tab character \tab Short display name. \cr
#'    name \tab character \tab Display name. \cr
#'    nickname \tab character \tab Team or athlete nickname. \cr
#'    location \tab character \tab Filter results by game location. \cr
#'    color \tab character \tab Primary color (hex without leading '#'). \cr
#'    alternate_color \tab character \tab Alternate color (hex without leading '#'). \cr
#'    logo \tab character \tab Team or league logo URL. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_team_info_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball team injuries injuries schema
#'
#' Columns shared verbatim across: espn_wbb_team_injuries, espn_wnba_team_injuries.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    team_id \tab character \tab Unique team identifier. \cr
#'    athlete_id \tab character \tab Unique athlete identifier (ESPN). \cr
#'    athlete_name \tab character \tab Athlete display name (ESPN). \cr
#'    position \tab character \tab Listed roster position (G, F, C, etc.). \cr
#'    status \tab character \tab Status label. \cr
#'    date \tab character \tab Date in YYYY-MM-DD format. \cr
#'    type \tab character \tab Record type / category. \cr
#'    side \tab character \tab Side label (e.g. 'home', 'away', or 'overUnder'). \cr
#'    returns_at \tab character \tab Returns at. \cr
#'    short_comment \tab character \tab Short comment. \cr
#'    long_comment \tab character \tab Long-form play / event comment. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_team_injuries_injuries_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball team leaders schema
#'
#' Columns shared verbatim across: espn_wbb_team_leaders, espn_wnba_team_leaders.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    team_id \tab character \tab Unique team identifier. \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    category \tab character \tab Category label. \cr
#'    display_name \tab character \tab Display name. \cr
#'    athlete_id \tab character \tab Unique athlete identifier (ESPN). \cr
#'    athlete_name \tab character \tab Athlete display name (ESPN). \cr
#'    value \tab numeric \tab Numeric or string value field. \cr
#'    rank \tab integer \tab Whether to include statistical ranks in the returned table. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_team_leaders_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball team roster schema
#'
#' Columns shared verbatim across: espn_wbb_team_roster, espn_wnba_team_roster.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    athlete_id \tab character \tab Unique athlete identifier (ESPN). \cr
#'    full_name \tab character \tab Player's full name. \cr
#'    jersey \tab character \tab Jersey number worn by the player. \cr
#'    position_abbrev \tab character \tab Abbreviation for position. \cr
#'    position_name \tab character \tab Listed roster position ('Guard', 'Forward', 'Center'). \cr
#'    height \tab character \tab Player height (string e.g. '6-2' or inches). \cr
#'    weight \tab character \tab Player weight in pounds. \cr
#'    age \tab character \tab Player age (in years). \cr
#'    birth_date \tab character \tab Date of birth (YYYY-MM-DD). \cr
#'    birth_place \tab character \tab Place of birth. \cr
#'    headshot \tab character \tab Headshot image URL. \cr
#'    link_web \tab character \tab Web link / URL. \cr
#'    status \tab character \tab Status label. \cr
#'    team_id \tab character \tab Unique team identifier. \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_team_roster_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball team schedule schema
#'
#' Columns shared verbatim across: espn_wbb_team_schedule, espn_wnba_team_schedule.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    event_id \tab character \tab Unique event / game identifier (ESPN). \cr
#'    season \tab integer \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    season_type \tab integer \tab Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). \cr
#'    week \tab integer \tab Week number within the season. \cr
#'    date \tab character \tab Date in YYYY-MM-DD format. \cr
#'    name \tab character \tab Display name. \cr
#'    short_name \tab character \tab Short display name. \cr
#'    opponent_id \tab character \tab Unique identifier for opponent. \cr
#'    opponent_abbrev \tab character \tab Abbreviation for opponent. \cr
#'    home_away \tab character \tab Game venue label ('home' or 'away'). \cr
#'    neutral_site \tab logical \tab Neutral site. \cr
#'    conference_competition \tab logical \tab Conference competition. \cr
#'    venue_id \tab character \tab Unique venue identifier. \cr
#'    venue_name \tab character \tab Venue name. \cr
#'    venue_city \tab character \tab Venue city. \cr
#'    venue_state \tab character \tab Venue state / region. \cr
#'    broadcast \tab character \tab Broadcast information string. \cr
#'    result \tab character \tab Result. \cr
#'    team_score \tab character \tab Team's score / final score. \cr
#'    opponent_score \tab character \tab Opponent score. \cr
#'    winner \tab logical \tab Winner. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_team_schedule_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball venues schema
#'
#' Columns shared verbatim across: espn_wbb_venues, espn_wnba_venues.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    venue_id \tab character \tab Unique venue identifier. \cr
#'    name \tab character \tab Display name. \cr
#'    full_name \tab character \tab Player's full name. \cr
#'    address_city \tab character \tab Address city. \cr
#'    address_state \tab character \tab Address state. \cr
#'    capacity \tab integer \tab Capacity. \cr
#'    indoor \tab logical \tab Indoor. \cr
#'    grass \tab logical \tab Grass. \cr
#'    images_url \tab character \tab URL for images. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_venues_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball week ranking schema
#'
#' Columns shared verbatim across: espn_wbb_week_ranking, espn_wnba_week_ranking.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    league \tab character \tab League slug. \cr
#'    season \tab integer \tab Season year. \cr
#'    season_type \tab integer \tab Season-type id. \cr
#'    week \tab integer \tab Week number. \cr
#'    ranking_id \tab character \tab ESPN ranking id. \cr
#'    name \tab character \tab Ranking name (e.g. "AP Top 25"). \cr
#'    short_name \tab character \tab Short name. \cr
#'    type \tab character \tab Ranking type code. \cr
#'    headline \tab character \tab Full headline. \cr
#'    date \tab character \tab Date of the ranking. \cr
#'    current \tab integer \tab Current rank. \cr
#'    previous \tab integer \tab Previous-week rank. \cr
#'    points \tab numeric \tab Voting points. \cr
#'    first_place_votes \tab integer \tab First-place vote count. \cr
#'    trend \tab character \tab Trend indicator (e.g. "+3", "-2", "-"). \cr
#'    record_summary \tab character \tab Team's record at time of poll (e.g. "20-2"). \cr
#'    team_id \tab character \tab ESPN team id. \cr
#'    team_ref \tab character \tab \verb{$ref} to the team-in-season resource. \cr
#'    last_updated \tab character \tab Last-updated timestamp. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name espn_basketball_week_ranking_schema
#' @keywords internal
NULL

#' Shared column schema: wnba boxscoresummaryv2 game summary schema
#'
#' Columns shared verbatim across: wnba_boxscoresummaryv2, wnba_scoreboard.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    GAME_DATE_EST \tab character \tab Game date est. \cr
#'    GAME_SEQUENCE \tab character \tab Game sequence. \cr
#'    GAME_ID \tab character \tab Unique game identifier. \cr
#'    GAME_STATUS_ID \tab character \tab Numeric game status identifier. \cr
#'    GAME_STATUS_TEXT \tab character \tab Game status display text (e.g. 'Final', '4:32 - 4th'). \cr
#'    GAMECODE \tab character \tab Gamecode. \cr
#'    HOME_TEAM_ID \tab character \tab Unique identifier for the home team. \cr
#'    VISITOR_TEAM_ID \tab character \tab Unique identifier for visitor team. \cr
#'    SEASON \tab character \tab Season identifier (4-digit year or 'YYYY-YY' string). \cr
#'    LIVE_PERIOD \tab character \tab Live period. \cr
#'    LIVE_PC_TIME \tab character \tab Time / clock value. \cr
#'    NATL_TV_BROADCASTER_ABBREVIATION \tab character \tab Natl tv broadcaster abbreviation. \cr
#'    LIVE_PERIOD_TIME_BCAST \tab character \tab Live period time bcast. \cr
#'    WH_STATUS \tab character \tab Wh status. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name wnba_boxscoresummaryv2_game_summary_schema
#' @keywords internal
NULL

#' Shared column schema: wnba boxscoresummaryv2 last meeting schema
#'
#' Columns shared verbatim across: wnba_boxscoresummaryv2, wnba_scoreboard, wnba_scoreboardv2.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    GAME_ID \tab character \tab Unique game identifier. \cr
#'    LAST_GAME_ID \tab character \tab  \cr
#'    LAST_GAME_DATE_EST \tab character \tab  \cr
#'    LAST_GAME_HOME_TEAM_ID \tab character \tab  \cr
#'    LAST_GAME_HOME_TEAM_CITY \tab character \tab  \cr
#'    LAST_GAME_HOME_TEAM_NAME \tab character \tab  \cr
#'    LAST_GAME_HOME_TEAM_ABBREVIATION \tab character \tab  \cr
#'    LAST_GAME_HOME_TEAM_POINTS \tab character \tab  \cr
#'    LAST_GAME_VISITOR_TEAM_ID \tab character \tab  \cr
#'    LAST_GAME_VISITOR_TEAM_CITY \tab character \tab  \cr
#'    LAST_GAME_VISITOR_TEAM_NAME \tab character \tab  \cr
#'    LAST_GAME_VISITOR_TEAM_CITY1 \tab character \tab  \cr
#'    LAST_GAME_VISITOR_TEAM_POINTS \tab character \tab  \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name wnba_boxscoresummaryv2_last_meeting_schema
#' @keywords internal
NULL

#' Shared column schema: wnba boxscoresummaryv2 season series schema
#'
#' Columns shared verbatim across: wnba_boxscoresummaryv2, wnba_scoreboard, wnba_scoreboardv2.
#'
#' |col_name |types |description |
#' |:----------------|:---------|:------------------------------------|
#' |GAME_ID |character |Unique game identifier. |
#' |HOME_TEAM_ID |character |Unique identifier for the home team. |
#' |VISITOR_TEAM_ID |character |Unique identifier for visitor team. |
#' |GAME_DATE_EST |character |Game date est. |
#' |HOME_TEAM_WINS |character |Home team's team wins. |
#' |HOME_TEAM_LOSSES |character |Home team's team losses. |
#' |SERIES_LEADER |character | |
#'
#' @name wnba_boxscoresummaryv2_season_series_schema
#' @keywords internal
NULL

#' Shared column schema: wnba homepagev2 home page stat1 schema
#'
#' Columns shared verbatim across: wnba_homepagev2, wnba_leaderstiles.
#'
#' |col_name |types |description |
#' |:-----------------|:---------|:-----------------------------------------------------------|
#' |RANK |character |Whether to include statistical ranks in the returned table. |
#' |TEAM_ID |character |Unique team identifier. |
#' |TEAM_ABBREVIATION |character |Short team abbreviation (e.g. 'LAS'). |
#' |TEAM_NAME |character |Full team display name (e.g. 'Las Vegas Aces'). |
#' |PTS |character |Points scored. |
#'
#' @name wnba_homepagev2_home_page_stat1_schema
#' @keywords internal
NULL

#' Shared column schema: wnba leaguedashteamclutch league dash team clutch schema
#'
#' Columns shared verbatim across: wnba_leaguedashteamclutch, wnba_leaguedashteamstats.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    TEAM_ID \tab character \tab Unique team identifier. \cr
#'    TEAM_NAME \tab character \tab Full team display name (e.g. 'Las Vegas Aces'). \cr
#'    GP \tab character \tab Games played. \cr
#'    W \tab character \tab Wins. \cr
#'    L \tab character \tab Losses. \cr
#'    W_PCT \tab character \tab Wins percentage (0-1 decimal). \cr
#'    MIN \tab character \tab Minutes played. \cr
#'    FGM \tab character \tab Field goals made. \cr
#'    FGA \tab character \tab Field goal attempts. \cr
#'    FG_PCT \tab character \tab Field goal percentage (0-1). \cr
#'    FG3M \tab character \tab Three-point field goals made. \cr
#'    FG3A \tab character \tab Three-point field goal attempts. \cr
#'    FG3_PCT \tab character \tab Three-point field goal percentage (0-1). \cr
#'    FTM \tab character \tab Free throws made. \cr
#'    FTA \tab character \tab Free throw attempts. \cr
#'    FT_PCT \tab character \tab Free throw percentage (0-1). \cr
#'    OREB \tab character \tab Offensive rebounds. \cr
#'    DREB \tab character \tab Defensive rebounds. \cr
#'    REB \tab character \tab Total rebounds. \cr
#'    AST \tab character \tab Assists. \cr
#'    TOV \tab character \tab Turnovers. \cr
#'    STL \tab character \tab Steals. \cr
#'    BLK \tab character \tab Blocks. \cr
#'    BLKA \tab character \tab  \cr
#'    PF \tab character \tab Personal fouls. \cr
#'    PFD \tab character \tab  \cr
#'    PTS \tab character \tab Points scored. \cr
#'    PLUS_MINUS \tab character \tab Plus/minus point differential while on court. \cr
#'    GP_RANK \tab character \tab  \cr
#'    W_RANK \tab character \tab  \cr
#'    L_RANK \tab character \tab  \cr
#'    W_PCT_RANK \tab character \tab  \cr
#'    MIN_RANK \tab character \tab  \cr
#'    FGM_RANK \tab character \tab  \cr
#'    FGA_RANK \tab character \tab  \cr
#'    FG_PCT_RANK \tab character \tab  \cr
#'    FG3M_RANK \tab character \tab  \cr
#'    FG3A_RANK \tab character \tab  \cr
#'    FG3_PCT_RANK \tab character \tab  \cr
#'    FTM_RANK \tab character \tab  \cr
#'    FTA_RANK \tab character \tab  \cr
#'    FT_PCT_RANK \tab character \tab  \cr
#'    OREB_RANK \tab character \tab  \cr
#'    DREB_RANK \tab character \tab  \cr
#'    REB_RANK \tab character \tab  \cr
#'    AST_RANK \tab character \tab  \cr
#'    TOV_RANK \tab character \tab  \cr
#'    STL_RANK \tab character \tab  \cr
#'    BLK_RANK \tab character \tab  \cr
#'    BLKA_RANK \tab character \tab  \cr
#'    PF_RANK \tab character \tab  \cr
#'    PFD_RANK \tab character \tab  \cr
#'    PTS_RANK \tab character \tab  \cr
#'    PLUS_MINUS_RANK \tab character \tab  \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name wnba_leaguedashteamclutch_league_dash_team_clutch_schema
#' @keywords internal
NULL

#' Shared column schema: wnba on off schema
#'
#' Columns shared verbatim across: wnba_leagueplayerondetails, wnba_teamplayeronoffdetails, wnba_teamvsplayer.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    GROUP_SET \tab character \tab  \cr
#'    TEAM_ID \tab character \tab Unique team identifier. \cr
#'    TEAM_ABBREVIATION \tab character \tab Short team abbreviation (e.g. 'LAS'). \cr
#'    TEAM_NAME \tab character \tab Full team display name (e.g. 'Las Vegas Aces'). \cr
#'    VS_PLAYER_ID \tab character \tab  \cr
#'    VS_PLAYER_NAME \tab character \tab  \cr
#'    COURT_STATUS \tab character \tab  \cr
#'    GP \tab character \tab Games played. \cr
#'    W \tab character \tab Wins. \cr
#'    L \tab character \tab Losses. \cr
#'    W_PCT \tab character \tab Wins percentage (0-1 decimal). \cr
#'    MIN \tab character \tab Minutes played. \cr
#'    FGM \tab character \tab Field goals made. \cr
#'    FGA \tab character \tab Field goal attempts. \cr
#'    FG_PCT \tab character \tab Field goal percentage (0-1). \cr
#'    FG3M \tab character \tab Three-point field goals made. \cr
#'    FG3A \tab character \tab Three-point field goal attempts. \cr
#'    FG3_PCT \tab character \tab Three-point field goal percentage (0-1). \cr
#'    FTM \tab character \tab Free throws made. \cr
#'    FTA \tab character \tab Free throw attempts. \cr
#'    FT_PCT \tab character \tab Free throw percentage (0-1). \cr
#'    OREB \tab character \tab Offensive rebounds. \cr
#'    DREB \tab character \tab Defensive rebounds. \cr
#'    REB \tab character \tab Total rebounds. \cr
#'    AST \tab character \tab Assists. \cr
#'    TOV \tab character \tab Turnovers. \cr
#'    STL \tab character \tab Steals. \cr
#'    BLK \tab character \tab Blocks. \cr
#'    BLKA \tab character \tab  \cr
#'    PF \tab character \tab Personal fouls. \cr
#'    PFD \tab character \tab  \cr
#'    PTS \tab character \tab Points scored. \cr
#'    PLUS_MINUS \tab character \tab Plus/minus point differential while on court. \cr
#'    GP_RANK \tab character \tab  \cr
#'    W_RANK \tab character \tab  \cr
#'    L_RANK \tab character \tab  \cr
#'    W_PCT_RANK \tab character \tab  \cr
#'    MIN_RANK \tab character \tab  \cr
#'    FGM_RANK \tab character \tab  \cr
#'    FGA_RANK \tab character \tab  \cr
#'    FG_PCT_RANK \tab character \tab  \cr
#'    FG3M_RANK \tab character \tab  \cr
#'    FG3A_RANK \tab character \tab  \cr
#'    FG3_PCT_RANK \tab character \tab  \cr
#'    FTM_RANK \tab character \tab  \cr
#'    FTA_RANK \tab character \tab  \cr
#'    FT_PCT_RANK \tab character \tab  \cr
#'    OREB_RANK \tab character \tab  \cr
#'    DREB_RANK \tab character \tab  \cr
#'    REB_RANK \tab character \tab  \cr
#'    AST_RANK \tab character \tab  \cr
#'    TOV_RANK \tab character \tab  \cr
#'    STL_RANK \tab character \tab  \cr
#'    BLK_RANK \tab character \tab  \cr
#'    BLKA_RANK \tab character \tab  \cr
#'    PF_RANK \tab character \tab  \cr
#'    PFD_RANK \tab character \tab  \cr
#'    PTS_RANK \tab character \tab  \cr
#'    PLUS_MINUS_RANK \tab character \tab  \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name wnba_on_off_schema
#' @keywords internal
NULL

#' Shared column schema: wnba player dashboard schema
#'
#' Columns shared verbatim across: wnba_playerdashboardbyclutch, wnba_playerdashboardbygamesplits, wnba_playerdashboardbygeneralsplits, wnba_playerdashboardbylastngames, wnba_playerdashboardbyopponent, wnba_playerdashboardbyteamperformance.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    GROUP_SET \tab character \tab  \cr
#'    GROUP_VALUE \tab character \tab  \cr
#'    GP \tab character \tab Games played. \cr
#'    W \tab character \tab Wins. \cr
#'    L \tab character \tab Losses. \cr
#'    W_PCT \tab character \tab Wins percentage (0-1 decimal). \cr
#'    MIN \tab character \tab Minutes played. \cr
#'    FGM \tab character \tab Field goals made. \cr
#'    FGA \tab character \tab Field goal attempts. \cr
#'    FG_PCT \tab character \tab Field goal percentage (0-1). \cr
#'    FG3M \tab character \tab Three-point field goals made. \cr
#'    FG3A \tab character \tab Three-point field goal attempts. \cr
#'    FG3_PCT \tab character \tab Three-point field goal percentage (0-1). \cr
#'    FTM \tab character \tab Free throws made. \cr
#'    FTA \tab character \tab Free throw attempts. \cr
#'    FT_PCT \tab character \tab Free throw percentage (0-1). \cr
#'    OREB \tab character \tab Offensive rebounds. \cr
#'    DREB \tab character \tab Defensive rebounds. \cr
#'    REB \tab character \tab Total rebounds. \cr
#'    AST \tab character \tab Assists. \cr
#'    TOV \tab character \tab Turnovers. \cr
#'    STL \tab character \tab Steals. \cr
#'    BLK \tab character \tab Blocks. \cr
#'    BLKA \tab character \tab  \cr
#'    PF \tab character \tab Personal fouls. \cr
#'    PFD \tab character \tab  \cr
#'    PTS \tab character \tab Points scored. \cr
#'    PLUS_MINUS \tab character \tab Plus/minus point differential while on court. \cr
#'    NBA_FANTASY_PTS \tab character \tab  \cr
#'    DD2 \tab character \tab  \cr
#'    TD3 \tab character \tab  \cr
#'    WNBA_FANTASY_PTS \tab character \tab  \cr
#'    GP_RANK \tab character \tab  \cr
#'    W_RANK \tab character \tab  \cr
#'    L_RANK \tab character \tab  \cr
#'    W_PCT_RANK \tab character \tab  \cr
#'    MIN_RANK \tab character \tab  \cr
#'    FGM_RANK \tab character \tab  \cr
#'    FGA_RANK \tab character \tab  \cr
#'    FG_PCT_RANK \tab character \tab  \cr
#'    FG3M_RANK \tab character \tab  \cr
#'    FG3A_RANK \tab character \tab  \cr
#'    FG3_PCT_RANK \tab character \tab  \cr
#'    FTM_RANK \tab character \tab  \cr
#'    FTA_RANK \tab character \tab  \cr
#'    FT_PCT_RANK \tab character \tab  \cr
#'    OREB_RANK \tab character \tab  \cr
#'    DREB_RANK \tab character \tab  \cr
#'    REB_RANK \tab character \tab  \cr
#'    AST_RANK \tab character \tab  \cr
#'    TOV_RANK \tab character \tab  \cr
#'    STL_RANK \tab character \tab  \cr
#'    BLK_RANK \tab character \tab  \cr
#'    BLKA_RANK \tab character \tab  \cr
#'    PF_RANK \tab character \tab  \cr
#'    PFD_RANK \tab character \tab  \cr
#'    PTS_RANK \tab character \tab  \cr
#'    PLUS_MINUS_RANK \tab character \tab  \cr
#'    NBA_FANTASY_PTS_RANK \tab character \tab  \cr
#'    DD2_RANK \tab character \tab  \cr
#'    TD3_RANK \tab character \tab  \cr
#'    WNBA_FANTASY_PTS_RANK \tab character \tab  \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name wnba_player_dashboard_schema
#' @keywords internal
NULL

#' Shared column schema: wnba playercareerstats season rankings schema
#'
#' Columns shared verbatim across: wnba_playercareerstats, wnba_playerprofilev2.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    PLAYER_ID \tab character \tab Unique player identifier. \cr
#'    SEASON_ID \tab character \tab Unique season identifier. \cr
#'    LEAGUE_ID \tab character \tab League identifier ('10' = WNBA). \cr
#'    TEAM_ID \tab character \tab Unique team identifier. \cr
#'    TEAM_ABBREVIATION \tab character \tab Short team abbreviation (e.g. 'LAS'). \cr
#'    PLAYER_AGE \tab character \tab  \cr
#'    GP \tab character \tab Games played. \cr
#'    GS \tab character \tab Games started. \cr
#'    RANK_MIN \tab character \tab  \cr
#'    RANK_FGM \tab character \tab  \cr
#'    RANK_FGA \tab character \tab  \cr
#'    RANK_FG_PCT \tab character \tab  \cr
#'    RANK_FG3M \tab character \tab  \cr
#'    RANK_FG3A \tab character \tab  \cr
#'    RANK_FG3_PCT \tab character \tab  \cr
#'    RANK_FTM \tab character \tab  \cr
#'    RANK_FTA \tab character \tab  \cr
#'    RANK_FT_PCT \tab character \tab  \cr
#'    RANK_OREB \tab character \tab  \cr
#'    RANK_DREB \tab character \tab  \cr
#'    RANK_REB \tab character \tab  \cr
#'    RANK_AST \tab character \tab  \cr
#'    RANK_STL \tab character \tab  \cr
#'    RANK_BLK \tab character \tab  \cr
#'    RANK_TOV \tab character \tab  \cr
#'    RANK_PTS \tab character \tab  \cr
#'    RANK_EFF \tab character \tab  \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name wnba_playercareerstats_season_rankings_schema
#' @keywords internal
NULL

#' Shared column schema: wnba playercareerstats season totals schema
#'
#' Columns shared verbatim across: wnba_playercareerstats, wnba_playerprofilev2.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    PLAYER_ID \tab character \tab Unique player identifier. \cr
#'    SEASON_ID \tab character \tab Unique season identifier. \cr
#'    LEAGUE_ID \tab character \tab League identifier ('10' = WNBA). \cr
#'    TEAM_ID \tab character \tab Unique team identifier. \cr
#'    TEAM_ABBREVIATION \tab character \tab Short team abbreviation (e.g. 'LAS'). \cr
#'    PLAYER_AGE \tab character \tab  \cr
#'    GP \tab character \tab Games played. \cr
#'    GS \tab character \tab Games started. \cr
#'    MIN \tab character \tab Minutes played. \cr
#'    FGM \tab character \tab Field goals made. \cr
#'    FGA \tab character \tab Field goal attempts. \cr
#'    FG_PCT \tab character \tab Field goal percentage (0-1). \cr
#'    FG3M \tab character \tab Three-point field goals made. \cr
#'    FG3A \tab character \tab Three-point field goal attempts. \cr
#'    FG3_PCT \tab character \tab Three-point field goal percentage (0-1). \cr
#'    FTM \tab character \tab Free throws made. \cr
#'    FTA \tab character \tab Free throw attempts. \cr
#'    FT_PCT \tab character \tab Free throw percentage (0-1). \cr
#'    OREB \tab character \tab Offensive rebounds. \cr
#'    DREB \tab character \tab Defensive rebounds. \cr
#'    REB \tab character \tab Total rebounds. \cr
#'    AST \tab character \tab Assists. \cr
#'    STL \tab character \tab Steals. \cr
#'    BLK \tab character \tab Blocks. \cr
#'    TOV \tab character \tab Turnovers. \cr
#'    PF \tab character \tab Personal fouls. \cr
#'    PTS \tab character \tab Points scored. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name wnba_playercareerstats_season_totals_schema
#' @keywords internal
NULL

#' Shared column schema: wnba players on court schema
#'
#' Columns shared verbatim across: .players_on_court, wnba_pbps.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    game_id \tab character \tab Unique game identifier. \cr
#'    event_num \tab character \tab Sequential event number within the game (V2 PBP). \cr
#'    event_type \tab character \tab Event / play type code (V2 PBP). \cr
#'    event_action_type \tab character \tab Numeric event-action-type code (V2 PBP). \cr
#'    period \tab numeric \tab Period of the game (1-4 quarters; 5+ for OT). \cr
#'    minute_game \tab numeric \tab Minute game. \cr
#'    time_remaining \tab numeric \tab Time remaining. \cr
#'    wc_time_string \tab character \tab Wc time string. \cr
#'    time_quarter \tab character \tab Time quarter. \cr
#'    minute_remaining_quarter \tab numeric \tab Minute remaining quarter. \cr
#'    seconds_remaining_quarter \tab numeric \tab Seconds remaining quarter. \cr
#'    home_description \tab character \tab Home team's description. \cr
#'    neutral_description \tab character \tab Neutral description. \cr
#'    visitor_description \tab character \tab Visitor description. \cr
#'    score \tab character \tab Final score. \cr
#'    away_score \tab numeric \tab Away team score at the time of the play. \cr
#'    home_score \tab numeric \tab Home team score at the time of the play. \cr
#'    score_margin \tab character \tab Score margin. \cr
#'    person1type \tab character \tab Person1type. \cr
#'    player1_id \tab character \tab V2 PBP primary player ID (e.g. shooter / fouler). \cr
#'    player1_name \tab character \tab V2 PBP primary player name. \cr
#'    player1_team_id \tab character \tab Team ID of player1. \cr
#'    player1_team_city \tab character \tab Player1 team city. \cr
#'    player1_team_nickname \tab character \tab Player1 team nickname. \cr
#'    player1_team_abbreviation \tab character \tab Player1 team abbreviation. \cr
#'    person2type \tab character \tab Person2type. \cr
#'    player2_id \tab character \tab V2 PBP secondary player ID (e.g. assister / fouled-by). \cr
#'    player2_name \tab character \tab V2 PBP secondary player name. \cr
#'    player2_team_id \tab character \tab Team ID of player2. \cr
#'    player2_team_city \tab character \tab Player2 team city. \cr
#'    player2_team_nickname \tab character \tab Player2 team nickname. \cr
#'    player2_team_abbreviation \tab character \tab Player2 team abbreviation. \cr
#'    person3type \tab character \tab Person3type. \cr
#'    player3_id \tab character \tab V2 PBP tertiary player ID (e.g. blocker). \cr
#'    player3_name \tab character \tab V2 PBP tertiary player name. \cr
#'    player3_team_id \tab character \tab Team ID of player3. \cr
#'    player3_team_city \tab character \tab Player3 team city. \cr
#'    player3_team_nickname \tab character \tab Player3 team nickname. \cr
#'    player3_team_abbreviation \tab character \tab Player3 team abbreviation. \cr
#'    video_available_flag \tab character \tab Video available flag. \cr
#'    team_leading \tab character \tab Team leading. \cr
#'    away_player1 \tab numeric \tab Away team's player1. \cr
#'    away_player2 \tab numeric \tab Away team's player2. \cr
#'    away_player3 \tab numeric \tab Away team's player3. \cr
#'    away_player4 \tab numeric \tab Away team's player4. \cr
#'    away_player5 \tab numeric \tab Away team's player5. \cr
#'    home_player1 \tab numeric \tab Home team's player1. \cr
#'    home_player2 \tab numeric \tab Home team's player2. \cr
#'    home_player3 \tab numeric \tab Home team's player3. \cr
#'    home_player4 \tab numeric \tab Home team's player4. \cr
#'    home_player5 \tab numeric \tab Home team's player5. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name wnba_players_on_court_schema
#' @keywords internal
NULL

#' Shared column schema: wnba scoreboard east conf standings by day schema
#'
#' Columns shared verbatim across: wnba_scoreboard, wnba_scoreboardv2.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    TEAM_ID \tab character \tab Unique team identifier. \cr
#'    LEAGUE_ID \tab character \tab League identifier ('10' = WNBA). \cr
#'    SEASON_ID \tab character \tab Unique season identifier. \cr
#'    STANDINGSDATE \tab character \tab  \cr
#'    CONFERENCE \tab character \tab Filter players or teams by conference. \cr
#'    TEAM \tab character \tab Team-side label or team identifier. \cr
#'    G \tab character \tab Games played. \cr
#'    W \tab character \tab Wins. \cr
#'    L \tab character \tab Losses. \cr
#'    W_PCT \tab character \tab Wins percentage (0-1 decimal). \cr
#'    HOME_RECORD \tab character \tab Home win-loss record. \cr
#'    ROAD_RECORD \tab character \tab Win-loss record for road. \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name wnba_scoreboard_east_conf_standings_by_day_schema
#' @keywords internal
NULL

#' Shared column schema: wnba shooting splits assisted by schema
#'
#' Columns shared verbatim across: wnba_playerdashboardbyshootingsplits, wnba_teamdashboardbyshootingsplits.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    GROUP_SET \tab character \tab  \cr
#'    PLAYER_ID \tab character \tab Unique player identifier. \cr
#'    PLAYER_NAME \tab character \tab Player name. \cr
#'    FGM \tab character \tab Field goals made. \cr
#'    FGA \tab character \tab Field goal attempts. \cr
#'    FG_PCT \tab character \tab Field goal percentage (0-1). \cr
#'    FG3M \tab character \tab Three-point field goals made. \cr
#'    FG3A \tab character \tab Three-point field goal attempts. \cr
#'    FG3_PCT \tab character \tab Three-point field goal percentage (0-1). \cr
#'    EFG_PCT \tab character \tab Effective field goal percentage (0-1). \cr
#'    BLKA \tab character \tab  \cr
#'    PCT_AST_2PM \tab character \tab  \cr
#'    PCT_UAST_2PM \tab character \tab  \cr
#'    PCT_AST_3PM \tab character \tab  \cr
#'    PCT_UAST_3PM \tab character \tab  \cr
#'    PCT_AST_FGM \tab character \tab  \cr
#'    PCT_UAST_FGM \tab character \tab  \cr
#'    FGM_RANK \tab character \tab  \cr
#'    FGA_RANK \tab character \tab  \cr
#'    FG_PCT_RANK \tab character \tab  \cr
#'    FG3M_RANK \tab character \tab  \cr
#'    FG3A_RANK \tab character \tab  \cr
#'    FG3_PCT_RANK \tab character \tab  \cr
#'    EFG_PCT_RANK \tab character \tab  \cr
#'    BLKA_RANK \tab character \tab  \cr
#'    PCT_AST_2PM_RANK \tab character \tab  \cr
#'    PCT_UAST_2PM_RANK \tab character \tab  \cr
#'    PCT_AST_3PM_RANK \tab character \tab  \cr
#'    PCT_UAST_3PM_RANK \tab character \tab  \cr
#'    PCT_AST_FGM_RANK \tab character \tab  \cr
#'    PCT_UAST_FGM_RANK \tab character \tab  \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name wnba_shooting_splits_assisted_by_schema
#' @keywords internal
NULL

#' Shared column schema: wnba shooting splits schema
#'
#' Columns shared verbatim across: wnba_playerdashboardbyshootingsplits, wnba_teamdashboardbyshootingsplits.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    GROUP_SET \tab character \tab  \cr
#'    GROUP_VALUE \tab character \tab  \cr
#'    FGM \tab character \tab Field goals made. \cr
#'    FGA \tab character \tab Field goal attempts. \cr
#'    FG_PCT \tab character \tab Field goal percentage (0-1). \cr
#'    FG3M \tab character \tab Three-point field goals made. \cr
#'    FG3A \tab character \tab Three-point field goal attempts. \cr
#'    FG3_PCT \tab character \tab Three-point field goal percentage (0-1). \cr
#'    EFG_PCT \tab character \tab Effective field goal percentage (0-1). \cr
#'    BLKA \tab character \tab  \cr
#'    PCT_AST_2PM \tab character \tab  \cr
#'    PCT_UAST_2PM \tab character \tab  \cr
#'    PCT_AST_3PM \tab character \tab  \cr
#'    PCT_UAST_3PM \tab character \tab  \cr
#'    PCT_AST_FGM \tab character \tab  \cr
#'    PCT_UAST_FGM \tab character \tab  \cr
#'    FGM_RANK \tab character \tab  \cr
#'    FGA_RANK \tab character \tab  \cr
#'    FG_PCT_RANK \tab character \tab  \cr
#'    FG3M_RANK \tab character \tab  \cr
#'    FG3A_RANK \tab character \tab  \cr
#'    FG3_PCT_RANK \tab character \tab  \cr
#'    EFG_PCT_RANK \tab character \tab  \cr
#'    BLKA_RANK \tab character \tab  \cr
#'    PCT_AST_2PM_RANK \tab character \tab  \cr
#'    PCT_UAST_2PM_RANK \tab character \tab  \cr
#'    PCT_AST_3PM_RANK \tab character \tab  \cr
#'    PCT_UAST_3PM_RANK \tab character \tab  \cr
#'    PCT_AST_FGM_RANK \tab character \tab  \cr
#'    PCT_UAST_FGM_RANK \tab character \tab  \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name wnba_shooting_splits_schema
#' @keywords internal
NULL

#' Shared column schema: wnba shotchartdetail league averages schema
#'
#' Columns shared verbatim across: wnba_shotchartdetail, wnba_shotchartleaguewide, wnba_shotchartlineupdetail.
#'
#' |col_name |types |description |
#' |:---------------|:---------|:---------------------------------------------------------------------|
#' |GRID_TYPE |character | |
#' |SHOT_ZONE_BASIC |character |Shot zone (e.g. 'Restricted Area', 'Mid-Range', 'Above the Break 3'). |
#' |SHOT_ZONE_AREA |character |Shot zone area ('Left Side', 'Right Side', 'Center'). |
#' |SHOT_ZONE_RANGE |character |Shot zone range ('Less Than 8 ft.', '8-16 ft.', '16-24 ft.', etc.). |
#' |FGA |character |Field goal attempts. |
#' |FGM |character |Field goals made. |
#' |FG_PCT |character |Field goal percentage (0-1). |
#'
#' @name wnba_shotchartdetail_league_averages_schema
#' @keywords internal
NULL

#' Shared column schema: wnba team dashboard schema
#'
#' Columns shared verbatim across: wnba_teamdashboardbyclutch, wnba_teamdashboardbygamesplits, wnba_teamdashboardbylastngames, wnba_teamdashboardbyopponent, wnba_teamdashboardbyteamperformance, wnba_teamdashboardbyyearoveryear.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    GROUP_SET \tab character \tab  \cr
#'    GROUP_VALUE \tab character \tab  \cr
#'    GP \tab character \tab Games played. \cr
#'    W \tab character \tab Wins. \cr
#'    L \tab character \tab Losses. \cr
#'    W_PCT \tab character \tab Wins percentage (0-1 decimal). \cr
#'    MIN \tab character \tab Minutes played. \cr
#'    FGM \tab character \tab Field goals made. \cr
#'    FGA \tab character \tab Field goal attempts. \cr
#'    FG_PCT \tab character \tab Field goal percentage (0-1). \cr
#'    FG3M \tab character \tab Three-point field goals made. \cr
#'    FG3A \tab character \tab Three-point field goal attempts. \cr
#'    FG3_PCT \tab character \tab Three-point field goal percentage (0-1). \cr
#'    FTM \tab character \tab Free throws made. \cr
#'    FTA \tab character \tab Free throw attempts. \cr
#'    FT_PCT \tab character \tab Free throw percentage (0-1). \cr
#'    OREB \tab character \tab Offensive rebounds. \cr
#'    DREB \tab character \tab Defensive rebounds. \cr
#'    REB \tab character \tab Total rebounds. \cr
#'    AST \tab character \tab Assists. \cr
#'    TOV \tab character \tab Turnovers. \cr
#'    STL \tab character \tab Steals. \cr
#'    BLK \tab character \tab Blocks. \cr
#'    BLKA \tab character \tab  \cr
#'    PF \tab character \tab Personal fouls. \cr
#'    PFD \tab character \tab  \cr
#'    PTS \tab character \tab Points scored. \cr
#'    PLUS_MINUS \tab character \tab Plus/minus point differential while on court. \cr
#'    GP_RANK \tab character \tab  \cr
#'    W_RANK \tab character \tab  \cr
#'    L_RANK \tab character \tab  \cr
#'    W_PCT_RANK \tab character \tab  \cr
#'    MIN_RANK \tab character \tab  \cr
#'    FGM_RANK \tab character \tab  \cr
#'    FGA_RANK \tab character \tab  \cr
#'    FG_PCT_RANK \tab character \tab  \cr
#'    FG3M_RANK \tab character \tab  \cr
#'    FG3A_RANK \tab character \tab  \cr
#'    FG3_PCT_RANK \tab character \tab  \cr
#'    FTM_RANK \tab character \tab  \cr
#'    FTA_RANK \tab character \tab  \cr
#'    FT_PCT_RANK \tab character \tab  \cr
#'    OREB_RANK \tab character \tab  \cr
#'    DREB_RANK \tab character \tab  \cr
#'    REB_RANK \tab character \tab  \cr
#'    AST_RANK \tab character \tab  \cr
#'    TOV_RANK \tab character \tab  \cr
#'    STL_RANK \tab character \tab  \cr
#'    BLK_RANK \tab character \tab  \cr
#'    BLKA_RANK \tab character \tab  \cr
#'    PF_RANK \tab character \tab  \cr
#'    PFD_RANK \tab character \tab  \cr
#'    PTS_RANK \tab character \tab  \cr
#'    PLUS_MINUS_RANK \tab character \tab  \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name wnba_team_dashboard_schema
#' @keywords internal
NULL

#' Shared column schema: wnba team summary overall schema
#'
#' Columns shared verbatim across: wnba_teamdashlineups, wnba_teamplayeronoffdetails, wnba_teamplayeronoffsummary.
#'
#' \if{html}{\tabular{lll}{
#'    col_name \tab types \tab description \cr
#'    GROUP_SET \tab character \tab  \cr
#'    GROUP_VALUE \tab character \tab  \cr
#'    TEAM_ID \tab character \tab Unique team identifier. \cr
#'    TEAM_ABBREVIATION \tab character \tab Short team abbreviation (e.g. 'LAS'). \cr
#'    TEAM_NAME \tab character \tab Full team display name (e.g. 'Las Vegas Aces'). \cr
#'    GP \tab character \tab Games played. \cr
#'    W \tab character \tab Wins. \cr
#'    L \tab character \tab Losses. \cr
#'    W_PCT \tab character \tab Wins percentage (0-1 decimal). \cr
#'    MIN \tab character \tab Minutes played. \cr
#'    FGM \tab character \tab Field goals made. \cr
#'    FGA \tab character \tab Field goal attempts. \cr
#'    FG_PCT \tab character \tab Field goal percentage (0-1). \cr
#'    FG3M \tab character \tab Three-point field goals made. \cr
#'    FG3A \tab character \tab Three-point field goal attempts. \cr
#'    FG3_PCT \tab character \tab Three-point field goal percentage (0-1). \cr
#'    FTM \tab character \tab Free throws made. \cr
#'    FTA \tab character \tab Free throw attempts. \cr
#'    FT_PCT \tab character \tab Free throw percentage (0-1). \cr
#'    OREB \tab character \tab Offensive rebounds. \cr
#'    DREB \tab character \tab Defensive rebounds. \cr
#'    REB \tab character \tab Total rebounds. \cr
#'    AST \tab character \tab Assists. \cr
#'    TOV \tab character \tab Turnovers. \cr
#'    STL \tab character \tab Steals. \cr
#'    BLK \tab character \tab Blocks. \cr
#'    BLKA \tab character \tab  \cr
#'    PF \tab character \tab Personal fouls. \cr
#'    PFD \tab character \tab  \cr
#'    PTS \tab character \tab Points scored. \cr
#'    PLUS_MINUS \tab character \tab Plus/minus point differential while on court. \cr
#'    GP_RANK \tab character \tab  \cr
#'    W_RANK \tab character \tab  \cr
#'    L_RANK \tab character \tab  \cr
#'    W_PCT_RANK \tab character \tab  \cr
#'    MIN_RANK \tab character \tab  \cr
#'    FGM_RANK \tab character \tab  \cr
#'    FGA_RANK \tab character \tab  \cr
#'    FG_PCT_RANK \tab character \tab  \cr
#'    FG3M_RANK \tab character \tab  \cr
#'    FG3A_RANK \tab character \tab  \cr
#'    FG3_PCT_RANK \tab character \tab  \cr
#'    FTM_RANK \tab character \tab  \cr
#'    FTA_RANK \tab character \tab  \cr
#'    FT_PCT_RANK \tab character \tab  \cr
#'    OREB_RANK \tab character \tab  \cr
#'    DREB_RANK \tab character \tab  \cr
#'    REB_RANK \tab character \tab  \cr
#'    AST_RANK \tab character \tab  \cr
#'    TOV_RANK \tab character \tab  \cr
#'    STL_RANK \tab character \tab  \cr
#'    BLK_RANK \tab character \tab  \cr
#'    BLKA_RANK \tab character \tab  \cr
#'    PF_RANK \tab character \tab  \cr
#'    PFD_RANK \tab character \tab  \cr
#'    PTS_RANK \tab character \tab  \cr
#'    PLUS_MINUS_RANK \tab character \tab  \cr
#' }}
#' \if{latex}{See the HTML help or pkgdown reference for the column table.}
#'
#' @name wnba_team_summary_overall_schema
#' @keywords internal
NULL

