## wehoop_schemas.R
## -------------------
## Shared column schemas referenced via [schema_name] links from
## multiple wehoop functions whose result-set tables are byte-identical.
## Generated by a one-time dedup pass (tools/docs/markdown_man_table_helper.R
## skips these topics on re-augmentation -- see the SKIP_SCHEMA_TOPICS guard
## in that file). Docs-only: no exports, `@keywords internal` throughout.

#' Shared column schema: basketball load wbb game rosters schema
#'
#' Columns shared verbatim across: load_wbb_game_rosters, load_wnba_game_rosters.
#'
#' |col_name |types |description |
#' |:--------------------|:---------|:---------------------------------------------------------------|
#' |game_id |character |Unique game identifier. |
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |team_id |character |Unique team identifier. |
#' |athlete_id |character |Unique athlete identifier (ESPN). |
#' |athlete_display_name |character |Athlete display name (full). |
#' |athlete_position |character |Athlete position. |
#' |athlete_jersey |character |Athlete jersey number. |
#' |starter |logical |TRUE if the player was in the starting lineup; FALSE otherwise. |
#' |did_not_play |logical |TRUE if the player did not appear in the game. |
#'
#' @name basketball_load_wbb_game_rosters_schema
#' @keywords internal
NULL

#' Shared column schema: basketball load wbb officials schema
#'
#' Columns shared verbatim across: load_wbb_officials, load_wnba_officials.
#'
#' |col_name |types |description |
#' |:------------|:---------|:-----------------------------------------------------|
#' |game_id |character |Unique game identifier. |
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |official_id |character |Unique official / referee identifier. |
#' |display_name |character |Display name. |
#' |full_name |character |Player's full name. |
#' |first_name |character |Player's first name. |
#' |last_name |character |Player's last name. |
#' |position |character |Listed roster position (G, F, C, etc.). |
#' |order |integer |Display order within the result set. |
#'
#' @name basketball_load_wbb_officials_schema
#' @keywords internal
NULL

#' Shared column schema: basketball load wbb shots schema
#'
#' Columns shared verbatim across: load_wbb_shots, load_wnba_shots.
#'
#' |col_name |types |description |
#' |:-------------------|:---------|:----------------------------------------------------------|
#' |game_id |character |Unique game identifier. |
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |period_number |integer |Numeric period (1-4 for quarters; 5+ for OT). |
#' |clock_display_value |character |Game clock display string (e.g. '8:32'). |
#' |team_id |character |Unique team identifier. |
#' |athlete_id_1 |character |Primary athlete identifier (e.g. shooter). |
#' |athlete_id_2 |character |Secondary athlete identifier (e.g. assister / fouler). |
#' |type_id |character |Type identifier (numeric). |
#' |type_text |character |Display text for the type field. |
#' |scoring_play |logical |TRUE if the play resulted in points scored. |
#' |score_value |integer |Point value of the play (2 / 3 / 1). |
#' |coordinate_x |numeric |X coordinate on the court (half-court layout). |
#' |coordinate_y |numeric |Y coordinate on the court (half-court layout). |
#' |coordinate_x_raw |numeric |X coordinate as returned by the API before any adjustment. |
#' |coordinate_y_raw |numeric |Y coordinate as returned by the API before any adjustment. |
#'
#' @name basketball_load_wbb_shots_schema
#' @keywords internal
NULL

#' Shared column schema: basketball load wbb standings schema
#'
#' Columns shared verbatim across: load_wbb_standings, load_wnba_standings.
#'
#' |col_name |types |description |
#' |:------------------|:---------|:------------------------------------------------------------------------------------------------------------------|
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |season_type |integer |Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). |
#' |team_id |character |Unique team identifier. |
#' |team_slug |character |URL-safe team identifier (e.g. 'lasvegas-aces' / 'aces'). |
#' |team_location |character |Team city or location string. |
#' |team_name |character |Full team display name (e.g. 'Las Vegas Aces'). |
#' |team_abbreviation |character |Short team abbreviation (e.g. 'LAS'). |
#' |team_display_name |character |Full team display name. |
#' |conference_id |character |Conference identifier. |
#' |conference_name |character |Full conference name. |
#' |wins |integer |Total wins. |
#' |losses |integer |Total losses. |
#' |win_percent |numeric |Win percent. |
#' |games_played |integer |Games played. |
#' |points_for |numeric |Points for. |
#' |points_against |numeric |Points allowed. |
#' |point_differential |numeric |Point differential. |
#' |streak |character |Current streak (e.g. 'W3' for three-game win streak). |
#'
#' @name basketball_load_wbb_standings_schema
#' @keywords internal
NULL

#' Shared column schema: basketball load wbb team stats schema
#'
#' Columns shared verbatim across: load_wbb_team_stats, load_wnba_team_stats.
#'
#' |col_name |types |description |
#' |:------------------|:---------|:------------------------------------------------------------------------------------------------------------------|
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |season_type |integer |Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). |
#' |team_id |character |Unique team identifier. |
#' |team_slug |character |URL-safe team identifier (e.g. 'lasvegas-aces' / 'aces'). |
#' |team_location |character |Team city or location string. |
#' |team_name |character |Full team display name (e.g. 'Las Vegas Aces'). |
#' |team_abbreviation |character |Short team abbreviation (e.g. 'LAS'). |
#' |team_display_name |character |Full team display name. |
#' |category |character |Category label. |
#' |stat_name |character |Stat name. |
#' |stat_display_name |character |Stat display name. |
#' |stat_value |numeric |Stat value. |
#' |stat_display_value |character |Stat display value. |
#' |stat_rank |integer |League/season rank for stat. |
#'
#' @name basketball_load_wbb_team_stats_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball athletes index schema
#'
#' Columns shared verbatim across: espn_wbb_athletes_index, espn_wnba_athletes_index.
#'
#' |col_name |types |description |
#' |:----------|:---------|:---------------------------------------|
#' |athlete_id |character |Unique athlete identifier (ESPN). |
#' |full_name |character |Player's full name. |
#' |jersey |character |Jersey number worn by the player. |
#' |position |character |Listed roster position (G, F, C, etc.). |
#' |team_id |character |Unique team identifier. |
#' |headshot |character |Headshot image URL. |
#' |status |character |Status label. |
#' |link |character |Link. |
#'
#' @name espn_basketball_athletes_index_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball calendar schema
#'
#' Columns shared verbatim across: espn_wbb_calendar, espn_wnba_calendar.
#'
#' |col_name |types |description |
#' |:-----------------|:---------|:------------------------------------------------------------------------------------------------------------------|
#' |season |character |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |season_type |character |Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). |
#' |season_type_label |character |Season type label. |
#' |season_start_date |character |Date in YYYY-MM-DD format. |
#' |season_end_date |character |Date in YYYY-MM-DD format. |
#' |label |character |Label. |
#' |alternate_label |character |Alternate label. |
#' |detail |character |Detail. |
#' |value |character |Numeric or string value field. |
#' |start_date |character |Start date (YYYY-MM-DD). |
#' |end_date |character |End date (YYYY-MM-DD). |
#'
#' @name espn_basketball_calendar_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball coach season schema
#'
#' Columns shared verbatim across: espn_wbb_coach_season, espn_wnba_coach_season.
#'
#' |col_name |types |description |
#' |:-------------|:---------|:------------------------------------------|
#' |league |character |League slug. |
#' |season |integer |Season year. |
#' |coach_id |character |ESPN coach id. |
#' |uid |character |ESPN UID string. |
#' |first_name |character |First name. |
#' |last_name |character |Last name. |
#' |date_of_birth |character |Date of birth. |
#' |birth_city |character |Birth city. |
#' |birth_state |character |Birth state / region. |
#' |n_records |integer |Count of records entries. |
#' |person_ref |character |`$ref` to person resource. |
#' |college_ref |character |`$ref` to college. |
#' |team_ref |character |`$ref` to team-in-season. |
#'
#' @name espn_basketball_coach_season_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball conferences schema
#'
#' Columns shared verbatim across: espn_wbb_conferences, espn_wnba_conferences.
#'
#' |col_name |types |description |
#' |:---------------------|:---------|:--------------------------------------------|
#' |group_id |integer |Group identifier (e.g. conference group_id). |
#' |conference_short_name |character |Conference short name (e.g. 'ACC'). |
#' |conference_uid |character |ESPN universal conference identifier. |
#' |conference_name |character |Full conference name. |
#' |conference_logo |character |Logo image URL for conference. |
#' |parent_group_id |integer |Unique identifier for parent group. |
#' |conference_id |integer |Conference identifier. |
#'
#' @name espn_basketball_conferences_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game all player player schema
#'
#' Columns shared verbatim across: espn_wbb_game_all, espn_wbb_player_box.
#'
#' |col_name |types |description |
#' |:---------------------------------|:---------|:------------------------------------------------------------------------------------------------------------------|
#' |game_id |integer |Unique game identifier. |
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |season_type |integer |Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). |
#' |game_date |Date |Game date (YYYY-MM-DD). |
#' |game_date_time |POSIXct |Game start date/time (ISO 8601). |
#' |athlete_id |integer |Unique athlete identifier (ESPN). |
#' |athlete_display_name |character |Athlete display name (full). |
#' |team_id |integer |Unique team identifier. |
#' |team_name |character |Full team display name (e.g. 'Las Vegas Aces'). |
#' |team_location |character |Team city or location string. |
#' |team_short_display_name |character |Short team display name (e.g. 'Aces'). |
#' |minutes |numeric |Minutes played, formatted MM:SS (V3 PT-duration parsed) or decimal minutes (V2). |
#' |field_goals_made |integer |Field goals made (2-pt + 3-pt). |
#' |field_goals_attempted |integer |Field goal attempts (2-pt + 3-pt). |
#' |three_point_field_goals_made |integer |Three-point field goals made. |
#' |three_point_field_goals_attempted |integer |Three-point field goal attempts. |
#' |free_throws_made |integer |Free throws made. |
#' |free_throws_attempted |integer |Free throw attempts. |
#' |offensive_rebounds |integer |Offensive rebounds. |
#' |defensive_rebounds |integer |Defensive rebounds. |
#' |rebounds |integer |Total rebounds. |
#' |assists |integer |Total assists. |
#' |steals |integer |Total steals. |
#' |blocks |integer |Total blocks. |
#' |turnovers |integer |Total turnovers. |
#' |fouls |integer |Personal fouls. |
#' |points |integer |Points scored. |
#' |starter |logical |TRUE if the player was in the starting lineup; FALSE otherwise. |
#' |ejected |logical |TRUE if the player was ejected from the game. |
#' |did_not_play |logical |TRUE if the player did not appear in the game. |
#' |active |logical |TRUE if the row represents an active record (player / team / season). |
#' |athlete_jersey |character |Athlete jersey number. |
#' |athlete_short_name |character |Athlete short display name. |
#' |athlete_headshot_href |character |Athlete headshot image URL. |
#' |athlete_position_name |character |Athlete position ('Guard', 'Forward', 'Center'). |
#' |athlete_position_abbreviation |character |Athlete position abbreviation (G / F / C). |
#' |team_display_name |character |Full team display name. |
#' |team_uid |character |ESPN universal team identifier (UID format 's:40~l:...~t:...'). |
#' |team_slug |character |URL-safe team identifier (e.g. 'lasvegas-aces' / 'aces'). |
#' |team_logo |character |Team logo image URL. |
#' |team_abbreviation |character |Short team abbreviation (e.g. 'LAS'). |
#' |team_color |character |Team primary color (hex without leading '#'). |
#' |team_alternate_color |character |Team alternate color (hex without leading '#'). |
#' |home_away |character |Game venue label ('home' or 'away'). |
#' |team_winner |logical |TRUE if the team won this game. |
#' |team_score |integer |Team's score / final score. |
#' |opponent_team_id |integer |Unique identifier for the opponent team. |
#' |opponent_team_name |character |Opponent team display name. |
#' |opponent_team_location |character |Opponent team city / location. |
#' |opponent_team_display_name |character |Opponent team full display name. |
#' |opponent_team_abbreviation |character |Opponent team abbreviation. |
#' |opponent_team_logo |character |Opponent team logo URL. |
#' |opponent_team_color |character |Opponent team primary color (hex). |
#' |opponent_team_alternate_color |character |Opponent team alternate color (hex). |
#' |opponent_team_score |integer |Opponent team's score. |
#'
#' @name espn_basketball_game_all_player_player_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game all player schema
#'
#' Columns shared verbatim across: espn_wnba_game_all, espn_wnba_player_box.
#'
#' |col_name |types |description |
#' |:---------------------------------|:---------|:------------------------------------------------------------------------------------------------------------------|
#' |game_id |integer |Unique game identifier. |
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |season_type |integer |Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). |
#' |game_date |Date |Game date (YYYY-MM-DD). |
#' |game_date_time |POSIXct |Game start date/time (ISO 8601). |
#' |athlete_id |integer |Unique athlete identifier (ESPN). |
#' |athlete_display_name |character |Athlete display name (full). |
#' |team_id |integer |Unique team identifier. |
#' |team_name |character |Full team display name (e.g. 'Las Vegas Aces'). |
#' |team_location |character |Team city or location string. |
#' |team_short_display_name |character |Short team display name (e.g. 'Aces'). |
#' |minutes |numeric |Minutes played, formatted MM:SS (V3 PT-duration parsed) or decimal minutes (V2). |
#' |field_goals_made |integer |Field goals made (2-pt + 3-pt). |
#' |field_goals_attempted |integer |Field goal attempts (2-pt + 3-pt). |
#' |three_point_field_goals_made |integer |Three-point field goals made. |
#' |three_point_field_goals_attempted |integer |Three-point field goal attempts. |
#' |free_throws_made |integer |Free throws made. |
#' |free_throws_attempted |integer |Free throw attempts. |
#' |offensive_rebounds |integer |Offensive rebounds. |
#' |defensive_rebounds |integer |Defensive rebounds. |
#' |rebounds |integer |Total rebounds. |
#' |assists |integer |Total assists. |
#' |steals |integer |Total steals. |
#' |blocks |integer |Total blocks. |
#' |turnovers |integer |Total turnovers. |
#' |fouls |integer |Personal fouls. |
#' |plus_minus |character |Plus/minus point differential while on court. |
#' |points |integer |Points scored. |
#' |starter |logical |TRUE if the player was in the starting lineup; FALSE otherwise. |
#' |ejected |logical |TRUE if the player was ejected from the game. |
#' |did_not_play |logical |TRUE if the player did not appear in the game. |
#' |reason |character |Reason. |
#' |active |logical |TRUE if the row represents an active record (player / team / season). |
#' |athlete_jersey |character |Athlete jersey number. |
#' |athlete_short_name |character |Athlete short display name. |
#' |athlete_headshot_href |character |Athlete headshot image URL. |
#' |athlete_position_name |character |Athlete position ('Guard', 'Forward', 'Center'). |
#' |athlete_position_abbreviation |character |Athlete position abbreviation (G / F / C). |
#' |team_display_name |character |Full team display name. |
#' |team_uid |character |ESPN universal team identifier (UID format 's:40~l:...~t:...'). |
#' |team_slug |character |URL-safe team identifier (e.g. 'lasvegas-aces' / 'aces'). |
#' |team_logo |character |Team logo image URL. |
#' |team_abbreviation |character |Short team abbreviation (e.g. 'LAS'). |
#' |team_color |character |Team primary color (hex without leading '#'). |
#' |team_alternate_color |character |Team alternate color (hex without leading '#'). |
#' |home_away |character |Game venue label ('home' or 'away'). |
#' |team_winner |logical |TRUE if the team won this game. |
#' |team_score |integer |Team's score / final score. |
#' |opponent_team_id |integer |Unique identifier for the opponent team. |
#' |opponent_team_name |character |Opponent team display name. |
#' |opponent_team_location |character |Opponent team city / location. |
#' |opponent_team_display_name |character |Opponent team full display name. |
#' |opponent_team_abbreviation |character |Opponent team abbreviation. |
#' |opponent_team_logo |character |Opponent team logo URL. |
#' |opponent_team_color |character |Opponent team primary color (hex). |
#' |opponent_team_alternate_color |character |Opponent team alternate color (hex). |
#' |opponent_team_score |integer |Opponent team's score. |
#'
#' @name espn_basketball_game_all_player_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game all plays plays schema
#'
#' Columns shared verbatim across: espn_wbb_game_all, espn_wbb_pbp.
#'
#' |col_name |types |description |
#' |:-------------------------|:---------|:------------------------------------------------------------------------------------------------------------------|
#' |id |character |Unique play identifcation number |
#' |sequence_number |character |Sequence number representing a shot-possession (V3 PBP). |
#' |text |character |Text description of the play / record. |
#' |away_score |integer |Away team score at the time of the play. |
#' |home_score |integer |Home team score at the time of the play. |
#' |scoring_play |logical |TRUE if the play resulted in points scored. |
#' |score_value |integer |Point value of the play (2 / 3 / 1). |
#' |wallclock |character |Wallclock. |
#' |shooting_play |logical |TRUE if the play was a shooting attempt. |
#' |type_id |integer |Type identifier (numeric). |
#' |type_text |character |Display text for the type field. |
#' |period_number |integer |Numeric period (1-4 for quarters; 5+ for OT). |
#' |period_display_value |character |Period display label (e.g. '1st Quarter', 'OT'). |
#' |clock_display_value |character |Game clock display string (e.g. '8:32'). |
#' |team_id |integer |Unique team identifier. |
#' |coordinate_x_raw |numeric |X coordinate as returned by the API before any adjustment. |
#' |coordinate_y_raw |numeric |Y coordinate as returned by the API before any adjustment. |
#' |coordinate_x |numeric |X coordinate on the court (half-court layout). |
#' |coordinate_y |numeric |Y coordinate on the court (half-court layout). |
#' |play_id |character |Unique play identifier within a game. |
#' |athlete_id_1 |integer |Primary athlete identifier (e.g. shooter). |
#' |athlete_id_2 |integer |Secondary athlete identifier (e.g. assister / fouler). |
#' |home_team_id |integer |Unique identifier for the home team. |
#' |home_team_mascot |character |Home team mascot. |
#' |home_team_name |character |Home team name. |
#' |home_team_abbrev |character |Home team three-letter abbreviation. |
#' |home_team_logo |character |Home team logo URL. |
#' |home_team_logo_dark |character |Home team logo URL for dark backgrounds. |
#' |home_team_full_name |character |Full home team name (e.g. 'Las Vegas Aces'). |
#' |home_team_color |character |Home team primary color (hex). |
#' |home_team_alternate_color |character |Home team alternate color (hex). |
#' |home_team_score |integer |Home team's score. |
#' |home_team_winner |logical |TRUE if the home team won this game. |
#' |home_team_record |character |Home team's win-loss record. |
#' |away_team_id |integer |Unique identifier for the away team. |
#' |away_team_mascot |character |Away team mascot. |
#' |away_team_name |character |Away team name. |
#' |away_team_abbrev |character |Away team three-letter abbreviation. |
#' |away_team_logo |character |Away team logo URL. |
#' |away_team_logo_dark |character |Away team logo URL for dark backgrounds. |
#' |away_team_full_name |character |Full away team name (e.g. 'Las Vegas Aces'). |
#' |away_team_color |character |Away team primary color (hex). |
#' |away_team_alternate_color |character |Away team alternate color (hex). |
#' |away_team_score |integer |Away team's score. |
#' |away_team_winner |logical |TRUE if the away team won this game. |
#' |away_team_record |character |Away team's win-loss record. |
#' |game_id |integer |Unique game identifier. |
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |season_type |integer |Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). |
#' |game_date |Date |Game date (YYYY-MM-DD). |
#' |game_date_time |POSIXct |Game start date/time (ISO 8601). |
#'
#' @name espn_basketball_game_all_plays_plays_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game all plays schema
#'
#' Columns shared verbatim across: espn_wnba_game_all, espn_wnba_pbp.
#'
#' |col_name |types |description |
#' |:-------------------------|:---------|:------------------------------------------------------------------------------------------------------------------|
#' |id |character |Unique play identifcation number |
#' |sequence_number |character |Sequence number representing a shot-possession (V3 PBP). |
#' |text |character |Text description of the play / record. |
#' |away_score |integer |Away team score at the time of the play. |
#' |home_score |integer |Home team score at the time of the play. |
#' |scoring_play |logical |TRUE if the play resulted in points scored. |
#' |score_value |integer |Point value of the play (2 / 3 / 1). |
#' |wallclock |character |Wallclock. |
#' |shooting_play |logical |TRUE if the play was a shooting attempt. |
#' |type_id |integer |Type identifier (numeric). |
#' |type_text |character |Display text for the type field. |
#' |period_number |integer |Numeric period (1-4 for quarters; 5+ for OT). |
#' |period_display_value |character |Period display label (e.g. '1st Quarter', 'OT'). |
#' |clock_display_value |character |Game clock display string (e.g. '8:32'). |
#' |team_id |integer |Unique team identifier. |
#' |coordinate_x_raw |numeric |X coordinate as returned by the API before any adjustment. |
#' |coordinate_y_raw |numeric |Y coordinate as returned by the API before any adjustment. |
#' |coordinate_x |numeric |X coordinate on the court (half-court layout). |
#' |coordinate_y |numeric |Y coordinate on the court (half-court layout). |
#' |play_id |character |Unique play identifier within a game. |
#' |athlete_id_1 |integer |Primary athlete identifier (e.g. shooter). |
#' |athlete_id_2 |integer |Secondary athlete identifier (e.g. assister / fouler). |
#' |athlete_id_3 |integer |Athlete id 3. |
#' |home_team_id |integer |Unique identifier for the home team. |
#' |home_team_mascot |character |Home team mascot. |
#' |home_team_name |character |Home team name. |
#' |home_team_abbrev |character |Home team three-letter abbreviation. |
#' |home_team_logo |character |Home team logo URL. |
#' |home_team_logo_dark |character |Home team logo URL for dark backgrounds. |
#' |home_team_full_name |character |Full home team name (e.g. 'Las Vegas Aces'). |
#' |home_team_color |character |Home team primary color (hex). |
#' |home_team_alternate_color |character |Home team alternate color (hex). |
#' |home_team_score |integer |Home team's score. |
#' |home_team_winner |logical |TRUE if the home team won this game. |
#' |home_team_record |character |Home team's win-loss record. |
#' |away_team_id |integer |Unique identifier for the away team. |
#' |away_team_mascot |character |Away team mascot. |
#' |away_team_name |character |Away team name. |
#' |away_team_abbrev |character |Away team three-letter abbreviation. |
#' |away_team_logo |character |Away team logo URL. |
#' |away_team_logo_dark |character |Away team logo URL for dark backgrounds. |
#' |away_team_full_name |character |Full away team name (e.g. 'Las Vegas Aces'). |
#' |away_team_color |character |Away team primary color (hex). |
#' |away_team_alternate_color |character |Away team alternate color (hex). |
#' |away_team_score |integer |Away team's score. |
#' |away_team_winner |logical |TRUE if the away team won this game. |
#' |away_team_record |character |Away team's win-loss record. |
#' |game_id |integer |Unique game identifier. |
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |season_type |integer |Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). |
#' |game_date |Date |Game date (YYYY-MM-DD). |
#' |game_date_time |POSIXct |Game start date/time (ISO 8601). |
#'
#' @name espn_basketball_game_all_plays_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game broadcasts schema
#'
#' Columns shared verbatim across: espn_wbb_game_broadcasts, espn_wnba_game_broadcasts.
#'
#' |col_name |types |description |
#' |:---------------|:---------|:--------------------------------------|
#' |event_id |character |Unique event / game identifier (ESPN). |
#' |broadcast_id |character |Unique identifier for broadcast. |
#' |type_id |character |Type identifier (numeric). |
#' |type_short_name |character |Type short name. |
#' |type_long_name |character |Type long name. |
#' |market_id |character |Unique identifier for market. |
#' |market_type |character |Market type. |
#' |names |character |Names. |
#' |lang |character |Lang. |
#' |region |character |Region label. |
#'
#' @name espn_basketball_game_broadcasts_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game odds schema
#'
#' Columns shared verbatim across: espn_wbb_game_odds, espn_wnba_game_odds.
#'
#' |col_name |types |description |
#' |:--------------------|:---------|:--------------------------------------|
#' |event_id |character |Unique event / game identifier (ESPN). |
#' |provider_id |character |Unique identifier for provider. |
#' |provider_name |character |Provider name. |
#' |details |character |Details. |
#' |over_under |numeric |Over under. |
#' |spread |numeric |Spread. |
#' |home_money_line |integer |Home team's money line. |
#' |away_money_line |integer |Away team's money line. |
#' |home_team_odds_open |numeric |Home team's team odds open. |
#' |home_team_odds_close |numeric |Home team's team odds close. |
#' |away_team_odds_open |numeric |Away team's team odds open. |
#' |away_team_odds_close |numeric |Away team's team odds close. |
#'
#' @name espn_basketball_game_odds_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game officials schema
#'
#' Columns shared verbatim across: espn_wbb_game_officials, espn_wnba_game_officials.
#'
#' |col_name |types |description |
#' |:-------------|:---------|:------------------------------------------------------|
#' |event_id |character |Unique event / game identifier (ESPN). |
#' |official_id |character |Unique official / referee identifier. |
#' |full_name |character |Player's full name. |
#' |display_name |character |Display name. |
#' |position_id |character |Unique position identifier. |
#' |position_name |character |Listed roster position ('Guard', 'Forward', 'Center'). |
#' |position_type |character |Position type. |
#' |order |integer |Display order within the result set. |
#'
#' @name espn_basketball_game_officials_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball game probabilities schema
#'
#' Columns shared verbatim across: espn_wbb_game_probabilities, espn_wnba_game_probabilities.
#'
#' |col_name |types |description |
#' |:---------------------|:---------|:--------------------------------------------------------|
#' |event_id |character |Unique event / game identifier (ESPN). |
#' |sequence_number |character |Sequence number representing a shot-possession (V3 PBP). |
#' |play_id |character |Unique play identifier within a game. |
#' |period |integer |Period of the game (1-4 quarters; 5+ for OT). |
#' |clock |character |Game clock value. |
#' |home_win_percentage |numeric |Home win percentage (0-1 decimal). |
#' |away_win_percentage |numeric |Away win percentage (0-1 decimal). |
#' |tie_percentage |numeric |Tie percentage (0-1 decimal). |
#' |secs_to_end_of_period |numeric |Secs to end of period. |
#' |secs_to_end_of_game |numeric |Secs to end of game. |
#'
#' @name espn_basketball_game_probabilities_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball injuries schema
#'
#' Columns shared verbatim across: espn_wbb_injuries, espn_wnba_injuries.
#'
#' |col_name |types |description |
#' |:-------------|:---------|:-----------------------------------------------------|
#' |team_id |character |Unique team identifier. |
#' |athlete_id |character |Unique athlete identifier (ESPN). |
#' |athlete_name |character |Athlete display name (ESPN). |
#' |position |character |Listed roster position (G, F, C, etc.). |
#' |status |character |Status label. |
#' |date |character |Date in YYYY-MM-DD format. |
#' |type |character |Record type / category. |
#' |side |character |Side label (e.g. 'home', 'away', or 'overUnder'). |
#' |returns_at |character |Returns at. |
#' |short_comment |character |Short comment. |
#' |long_comment |character |Long-form play / event comment. |
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#'
#' @name espn_basketball_injuries_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball leaders schema
#'
#' Columns shared verbatim across: espn_wbb_leaders, espn_wnba_leaders.
#'
#' |col_name |types |description |
#' |:-------------|:---------|:------------------------------------------------------------------------------------------------------------------|
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |season_type |integer |Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). |
#' |category |character |Category label. |
#' |abbreviation |character |Short abbreviation. |
#' |athlete_id |character |Unique athlete identifier (ESPN). |
#' |athlete_name |character |Athlete display name (ESPN). |
#' |team_id |character |Unique team identifier. |
#' |team_abbrev |character |Abbreviation for team. |
#' |value |numeric |Numeric or string value field. |
#' |rank |integer |Whether to include statistical ranks in the returned table. |
#' |display_value |character |Human-readable display value. |
#'
#' @name espn_basketball_leaders_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball news schema
#'
#' Columns shared verbatim across: espn_wbb_news, espn_wbb_team_news, espn_wnba_news, espn_wnba_team_news.
#'
#' |col_name |types |description |
#' |:-----------|:---------|:---------------------------------|
#' |id |character |Unique play identifcation number |
#' |type |character |Record type / category. |
#' |headline |character |News headline. |
#' |description |character |Long-form description text. |
#' |published |character |Publication timestamp (ISO 8601). |
#' |premium |logical |Premium. |
#' |byline |character |News article byline / author. |
#' |link_web |character |Web link / URL. |
#' |league_id |character |League identifier ('10' = WNBA). |
#'
#' @name espn_basketball_news_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball player awards schema
#'
#' Columns shared verbatim across: espn_wbb_player_awards, espn_wnba_player_awards.
#'
#' |col_name |types |description |
#' |:-----------|:---------|:-----------------------------------------------------|
#' |season |character |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |award_id |character |Unique identifier for award. |
#' |name |character |Display name. |
#' |description |character |Long-form description text. |
#' |date |character |Date in YYYY-MM-DD format. |
#' |type |character |Record type / category. |
#'
#' @name espn_basketball_player_awards_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball player career stats schema
#'
#' Columns shared verbatim across: espn_wbb_player_career_stats, espn_wnba_player_career_stats.
#'
#' |col_name |types |description |
#' |:----------------|:---------|:------------------------------------------|
#' |league |character |League slug. |
#' |athlete_id |character |ESPN athlete id. |
#' |stat_type_id |character |Stat-type code (0 = reg, 1 = post, 2 = career). |
#' |split_id |character |Split id. |
#' |split_name |character |Split name (typically "All Splits"). |
#' |split_type |character |Split type code. |
#' |category_name |character |Category key (e.g. "defensive"). |
#' |category_display |character |Category display name. |
#' |category_short |character |Category short display. |
#' |category_abbrev |character |Category abbreviation. |
#' |stat_name |character |Stat key. |
#' |stat_abbrev |character |Stat abbreviation. |
#' |stat_display |character |Stat display name. |
#' |stat_short |character |Stat short display. |
#' |description |character |Stat description. |
#' |value |numeric |Stat value. |
#' |display_value |character |Display-formatted value. |
#'
#' @name espn_basketball_player_career_stats_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball player info bio schema
#'
#' Columns shared verbatim across: espn_wbb_player_info, espn_wnba_player_info.
#'
#' |col_name |types |description |
#' |:-------------|:---------|:---------------------------------|
#' |id |character |Unique play identifcation number |
#' |full_name |character |Player's full name. |
#' |display_name |character |Display name. |
#' |jersey |character |Jersey number worn by the player. |
#' |age |character |Player age (in years). |
#' |date_of_birth |character |Date of birth (YYYY-MM-DD). |
#' |headshot_href |character |Headshot image URL. |
#'
#' @name espn_basketball_player_info_bio_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball player overview next game schema
#'
#' Columns shared verbatim across: espn_wbb_player_overview, espn_wbb_team, espn_wnba_player_overview, espn_wnba_team.
#'
#' |col_name |types |description |
#' |:----------|:---------|:--------------------------------|
#' |id |character |Unique play identifcation number |
#' |date |character |Date in YYYY-MM-DD format. |
#' |name |character |Display name. |
#' |short_name |character |Short display name. |
#'
#' @name espn_basketball_player_overview_next_game_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball player overview statistics schema
#'
#' Columns shared verbatim across: espn_wbb_player_overview, espn_wnba_player_overview.
#'
#' |col_name |types |description |
#' |:--------|:---------|:-----------|
#' |(varies) |character | |
#'
#' @name espn_basketball_player_overview_statistics_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball scoreboard schema
#'
#' Columns shared verbatim across: espn_wbb_scoreboard, espn_wnba_scoreboard.
#'
#' |col_name |types |description |
#' |:-------------------|:---------|:------------------------------------------------------------------------------------------------------------------|
#' |matchup |character |Matchup. |
#' |matchup_short |character |Matchup short. |
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |season_type |integer |Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). |
#' |season_slug |character |Season slug. |
#' |game_id |integer |Unique game identifier. |
#' |game_uid |character |Game uid. |
#' |game_date |Date |Game date (YYYY-MM-DD). |
#' |attendance |integer |Reported attendance. |
#' |status_name |character |Status label. |
#' |broadcast_market |character |Broadcast market label (e.g. 'national', 'home'). |
#' |broadcast_name |character |Broadcast name. |
#' |start_date |character |Start date (YYYY-MM-DD). |
#' |game_date_time |POSIXct |Game start date/time (ISO 8601). |
#' |home_team_name |character |Home team name. |
#' |home_team_logo |character |Home team logo URL. |
#' |home_team_abb |character |Home team's team abb. |
#' |home_team_id |integer |Unique identifier for the home team. |
#' |home_team_location |character |Home team's team location. |
#' |home_team_full_name |character |Full home team name (e.g. 'Las Vegas Aces'). |
#' |home_team_color |character |Home team primary color (hex). |
#' |home_score |integer |Home team score at the time of the play. |
#' |home_win |integer |Home team's win. |
#' |home_record |character |Home win-loss record. |
#' |away_team_name |character |Away team name. |
#' |away_team_logo |character |Away team logo URL. |
#' |away_team_abb |character |Away team's team abb. |
#' |away_team_id |integer |Unique identifier for the away team. |
#' |away_team_location |character |Away team's team location. |
#' |away_team_full_name |character |Full away team name (e.g. 'Las Vegas Aces'). |
#' |away_team_color |character |Away team primary color (hex). |
#' |away_score |integer |Away team score at the time of the play. |
#' |away_win |integer |Away team's win. |
#' |away_record |character |Away win-loss record. |
#'
#' @name espn_basketball_scoreboard_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball season group schema
#'
#' Columns shared verbatim across: espn_wbb_season_group, espn_wnba_season_group.
#'
#' |col_name |types |description |
#' |:--------------|:---------|:------------------------------------------|
#' |league |character |League slug. |
#' |season |integer |Season year. |
#' |season_type |integer |Season-type id. |
#' |group_id |character |ESPN group id. |
#' |uid |character |ESPN UID string. |
#' |name |character |Full name (e.g. "Eastern Conference"). |
#' |abbreviation |character |Short code (e.g. "EAST"). |
#' |short_name |character |Short name. |
#' |midsize_name |character |Mid-size display name. |
#' |is_conference |logical |Whether this group is a conference. |
#' |slug |character |URL slug. |
#' |parent_ref |character |`$ref` to parent group (if any). |
#' |children_ref |character |`$ref` to child-groups endpoint. |
#' |teams_ref |character |`$ref` to teams-in-group endpoint. |
#' |standings_ref |character |`$ref` to standings endpoint. |
#'
#' @name espn_basketball_season_group_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball season leaders schema
#'
#' Columns shared verbatim across: espn_wbb_season_leaders, espn_wnba_season_leaders.
#'
#' |col_name |types |description |
#' |:----------------|:---------|:----------------------------------------|
#' |league |character |League slug. |
#' |season |integer |Season year. |
#' |season_type |integer |Season-type id. |
#' |category_name |character |Internal category key (e.g. "pointsPerGame"). |
#' |category_display |character |Human-readable category name. |
#' |category_short |character |Short display name. |
#' |category_abbrev |character |Stat abbreviation (e.g. "PTS"). |
#' |rank |integer |Rank within the category (1 = best). |
#' |athlete_id |character |ESPN athlete id. |
#' |team_id |character |ESPN team id. |
#' |display_value |character |Display-formatted value. |
#' |value |numeric |Numeric leader value. |
#' |rel |character |Comma-joined `rel` tags from ESPN. |
#' |athlete_ref |character |`$ref` URL to the leader's athlete. |
#' |team_ref |character |`$ref` URL to the leader's team. |
#'
#' @name espn_basketball_season_leaders_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball season ranking schema
#'
#' Columns shared verbatim across: espn_wbb_season_ranking, espn_wnba_season_ranking.
#'
#' |col_name |types |description |
#' |:-----------|:---------|:------------------------------------------|
#' |league |character |League slug. |
#' |season |integer |Season year. |
#' |ranking_id |character |ESPN ranking id. |
#' |name |character |Ranking name (e.g. "AP Top 25"). |
#' |short_name |character |Short name (e.g. "AP Poll"). |
#' |type |character |Ranking type code (e.g. "ap"). |
#' |season_type |integer |Season-type id of this snapshot. |
#' |week |integer |Week number of this snapshot. |
#' |ref |character |`$ref` URL for the per-week ranking detail.|
#'
#' @name espn_basketball_season_ranking_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball season type schema
#'
#' Columns shared verbatim across: espn_wbb_season_type, espn_wnba_season_type.
#'
#' |col_name |types |description |
#' |:-------------|:---------|:------------------------------------------|
#' |league |character |League slug. |
#' |season |integer |Season year. |
#' |season_type |integer |Season-type id. |
#' |type |integer |Numeric type code. |
#' |name |character |Display name (e.g. "Regular Season"). |
#' |abbreviation |character |Short code (e.g. "reg"). |
#' |year |integer |Year stamp. |
#' |start_date |character |ISO 8601 start date. |
#' |end_date |character |ISO 8601 end date. |
#' |has_groups |logical |Whether groups exist for this type. |
#' |has_standings |logical |Whether standings exist. |
#' |has_legs |logical |Whether playoff legs exist. |
#' |slug |character |URL slug. |
#' |groups_ref |character |`$ref` to the groups endpoint. |
#' |weeks_ref |character |`$ref` to the weeks endpoint. |
#' |leaders_ref |character |`$ref` to the leaders endpoint. |
#'
#' @name espn_basketball_season_type_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball season week schema
#'
#' Columns shared verbatim across: espn_wbb_season_week, espn_wnba_season_week.
#'
#' |col_name |types |description |
#' |:------------|:---------|:------------------------------------------|
#' |league |character |League slug. |
#' |season |integer |Season year. |
#' |season_type |integer |Season-type id. |
#' |week |integer |Week number. |
#' |text |character |Display label (e.g. "Week 5"). |
#' |start_date |character |ISO 8601 week start. |
#' |end_date |character |ISO 8601 week end. |
#' |rankings_ref |character |`$ref` to the per-week rankings endpoint. |
#'
#' @name espn_basketball_season_week_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball team box schema
#'
#' Columns shared verbatim across: espn_wbb_game_all, espn_wbb_team_box, espn_wnba_game_all, espn_wnba_team_box.
#'
#' |col_name |types |description |
#' |:---------------------------------|:---------|:------------------------------------------------------------------------------------------------------------------|
#' |game_id |integer |Unique game identifier. |
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |season_type |integer |Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). |
#' |game_date |Date |Game date (YYYY-MM-DD). |
#' |game_date_time |POSIXct |Game start date/time (ISO 8601). |
#' |team_id |integer |Unique team identifier. |
#' |team_uid |character |ESPN universal team identifier (UID format 's:40~l:...~t:...'). |
#' |team_slug |character |URL-safe team identifier (e.g. 'lasvegas-aces' / 'aces'). |
#' |team_location |character |Team city or location string. |
#' |team_name |character |Full team display name (e.g. 'Las Vegas Aces'). |
#' |team_abbreviation |character |Short team abbreviation (e.g. 'LAS'). |
#' |team_display_name |character |Full team display name. |
#' |team_short_display_name |character |Short team display name (e.g. 'Aces'). |
#' |team_color |character |Team primary color (hex without leading '#'). |
#' |team_alternate_color |character |Team alternate color (hex without leading '#'). |
#' |team_logo |character |Team logo image URL. |
#' |team_home_away |character |Team home away. |
#' |team_score |integer |Team's score / final score. |
#' |team_winner |logical |TRUE if the team won this game. |
#' |assists |integer |Total assists. |
#' |blocks |integer |Total blocks. |
#' |defensive_rebounds |integer |Defensive rebounds. |
#' |field_goal_pct |numeric |Field goal percentage (0-1). |
#' |field_goals_made |integer |Field goals made (2-pt + 3-pt). |
#' |field_goals_attempted |integer |Field goal attempts (2-pt + 3-pt). |
#' |flagrant_fouls |integer |Total flagrant fouls. |
#' |fouls |integer |Personal fouls. |
#' |free_throw_pct |numeric |Free throw percentage (0-1). |
#' |free_throws_made |integer |Free throws made. |
#' |free_throws_attempted |integer |Free throw attempts. |
#' |largest_lead |character |Largest lead during the game. |
#' |offensive_rebounds |integer |Offensive rebounds. |
#' |steals |integer |Total steals. |
#' |team_turnovers |integer |Team turnovers (turnovers credited to the team rather than a player). |
#' |technical_fouls |integer |Total technical fouls. |
#' |three_point_field_goal_pct |numeric |Three-point field goal percentage (0-1). |
#' |three_point_field_goals_made |integer |Three-point field goals made. |
#' |three_point_field_goals_attempted |integer |Three-point field goal attempts. |
#' |total_rebounds |integer |Total rebounds. |
#' |total_technical_fouls |integer |Total technical fouls (player + team). |
#' |total_turnovers |integer |Total turnovers (player + team). |
#' |turnovers |integer |Total turnovers. |
#' |opponent_team_id |integer |Unique identifier for the opponent team. |
#' |opponent_team_uid |character |Opponent team uid. |
#' |opponent_team_slug |character |Opponent team slug. |
#' |opponent_team_location |character |Opponent team city / location. |
#' |opponent_team_name |character |Opponent team display name. |
#' |opponent_team_abbreviation |character |Opponent team abbreviation. |
#' |opponent_team_display_name |character |Opponent team full display name. |
#' |opponent_team_short_display_name |character |Opponent team short display name. |
#' |opponent_team_color |character |Opponent team primary color (hex). |
#' |opponent_team_alternate_color |character |Opponent team alternate color (hex). |
#' |opponent_team_logo |character |Opponent team logo URL. |
#' |opponent_team_score |integer |Opponent team's score. |
#'
#' @name espn_basketball_team_box_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball team info schema
#'
#' Columns shared verbatim across: espn_wbb_team, espn_wnba_team.
#'
#' |col_name |types |description |
#' |:------------------|:---------|:------------------------------------------|
#' |id |character |Unique play identifcation number |
#' |uid |character |ESPN UID string (universal identifier). |
#' |slug |character |URL-safe identifier. |
#' |abbreviation |character |Short abbreviation. |
#' |display_name |character |Display name. |
#' |short_display_name |character |Short display name. |
#' |name |character |Display name. |
#' |nickname |character |Team or athlete nickname. |
#' |location |character |Filter results by game location. |
#' |color |character |Primary color (hex without leading '#'). |
#' |alternate_color |character |Alternate color (hex without leading '#'). |
#' |logo |character |Team or league logo URL. |
#'
#' @name espn_basketball_team_info_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball team injuries injuries schema
#'
#' Columns shared verbatim across: espn_wbb_team_injuries, espn_wnba_team_injuries.
#'
#' |col_name |types |description |
#' |:-------------|:---------|:-------------------------------------------------|
#' |team_id |character |Unique team identifier. |
#' |athlete_id |character |Unique athlete identifier (ESPN). |
#' |athlete_name |character |Athlete display name (ESPN). |
#' |position |character |Listed roster position (G, F, C, etc.). |
#' |status |character |Status label. |
#' |date |character |Date in YYYY-MM-DD format. |
#' |type |character |Record type / category. |
#' |side |character |Side label (e.g. 'home', 'away', or 'overUnder'). |
#' |returns_at |character |Returns at. |
#' |short_comment |character |Short comment. |
#' |long_comment |character |Long-form play / event comment. |
#'
#' @name espn_basketball_team_injuries_injuries_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball team leaders schema
#'
#' Columns shared verbatim across: espn_wbb_team_leaders, espn_wnba_team_leaders.
#'
#' |col_name |types |description |
#' |:------------|:---------|:-----------------------------------------------------------|
#' |team_id |character |Unique team identifier. |
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |category |character |Category label. |
#' |display_name |character |Display name. |
#' |athlete_id |character |Unique athlete identifier (ESPN). |
#' |athlete_name |character |Athlete display name (ESPN). |
#' |value |numeric |Numeric or string value field. |
#' |rank |integer |Whether to include statistical ranks in the returned table. |
#'
#' @name espn_basketball_team_leaders_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball team roster schema
#'
#' Columns shared verbatim across: espn_wbb_team_roster, espn_wnba_team_roster.
#'
#' |col_name |types |description |
#' |:---------------|:---------|:------------------------------------------------------|
#' |athlete_id |character |Unique athlete identifier (ESPN). |
#' |full_name |character |Player's full name. |
#' |jersey |character |Jersey number worn by the player. |
#' |position_abbrev |character |Abbreviation for position. |
#' |position_name |character |Listed roster position ('Guard', 'Forward', 'Center'). |
#' |height |character |Player height (string e.g. '6-2' or inches). |
#' |weight |character |Player weight in pounds. |
#' |age |character |Player age (in years). |
#' |birth_date |character |Date of birth (YYYY-MM-DD). |
#' |birth_place |character |Place of birth. |
#' |headshot |character |Headshot image URL. |
#' |link_web |character |Web link / URL. |
#' |status |character |Status label. |
#' |team_id |character |Unique team identifier. |
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#'
#' @name espn_basketball_team_roster_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball team schedule schema
#'
#' Columns shared verbatim across: espn_wbb_team_schedule, espn_wnba_team_schedule.
#'
#' |col_name |types |description |
#' |:----------------------|:---------|:------------------------------------------------------------------------------------------------------------------|
#' |event_id |character |Unique event / game identifier (ESPN). |
#' |season |integer |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |season_type |integer |Season type (1=pre-season, 2=regular season, 3=postseason, 4=off-season for ESPN; or string label for WNBA Stats). |
#' |week |integer |Week number within the season. |
#' |date |character |Date in YYYY-MM-DD format. |
#' |name |character |Display name. |
#' |short_name |character |Short display name. |
#' |opponent_id |character |Unique identifier for opponent. |
#' |opponent_abbrev |character |Abbreviation for opponent. |
#' |home_away |character |Game venue label ('home' or 'away'). |
#' |neutral_site |logical |Neutral site. |
#' |conference_competition |logical |Conference competition. |
#' |venue_id |character |Unique venue identifier. |
#' |venue_name |character |Venue name. |
#' |venue_city |character |Venue city. |
#' |venue_state |character |Venue state / region. |
#' |broadcast |character |Broadcast information string. |
#' |result |character |Result. |
#' |team_score |character |Team's score / final score. |
#' |opponent_score |character |Opponent score. |
#' |winner |logical |Winner. |
#'
#' @name espn_basketball_team_schedule_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball venues schema
#'
#' Columns shared verbatim across: espn_wbb_venues, espn_wnba_venues.
#'
#' |col_name |types |description |
#' |:-------------|:---------|:------------------------|
#' |venue_id |character |Unique venue identifier. |
#' |name |character |Display name. |
#' |full_name |character |Player's full name. |
#' |address_city |character |Address city. |
#' |address_state |character |Address state. |
#' |capacity |integer |Capacity. |
#' |indoor |logical |Indoor. |
#' |grass |logical |Grass. |
#' |images_url |character |URL for images. |
#'
#' @name espn_basketball_venues_schema
#' @keywords internal
NULL

#' Shared column schema: espn basketball week ranking schema
#'
#' Columns shared verbatim across: espn_wbb_week_ranking, espn_wnba_week_ranking.
#'
#' |col_name |types |description |
#' |:------------------|:---------|:------------------------------------------|
#' |league |character |League slug. |
#' |season |integer |Season year. |
#' |season_type |integer |Season-type id. |
#' |week |integer |Week number. |
#' |ranking_id |character |ESPN ranking id. |
#' |name |character |Ranking name (e.g. "AP Top 25"). |
#' |short_name |character |Short name. |
#' |type |character |Ranking type code. |
#' |headline |character |Full headline. |
#' |date |character |Date of the ranking. |
#' |current |integer |Current rank. |
#' |previous |integer |Previous-week rank. |
#' |points |numeric |Voting points. |
#' |first_place_votes |integer |First-place vote count. |
#' |trend |character |Trend indicator (e.g. "+3", "-2", "-"). |
#' |record_summary |character |Team's record at time of poll (e.g. "20-2").|
#' |team_id |character |ESPN team id. |
#' |team_ref |character |`$ref` to the team-in-season resource. |
#' |last_updated |character |Last-updated timestamp. |
#'
#' @name espn_basketball_week_ranking_schema
#' @keywords internal
NULL

#' Shared column schema: wnba boxscoresummaryv2 game summary schema
#'
#' Columns shared verbatim across: wnba_boxscoresummaryv2, wnba_scoreboard.
#'
#' |col_name |types |description |
#' |:--------------------------------|:---------|:------------------------------------------------------|
#' |GAME_DATE_EST |character |Game date est. |
#' |GAME_SEQUENCE |character |Game sequence. |
#' |GAME_ID |character |Unique game identifier. |
#' |GAME_STATUS_ID |character |Numeric game status identifier. |
#' |GAME_STATUS_TEXT |character |Game status display text (e.g. 'Final', '4:32 - 4th'). |
#' |GAMECODE |character |Gamecode. |
#' |HOME_TEAM_ID |character |Unique identifier for the home team. |
#' |VISITOR_TEAM_ID |character |Unique identifier for visitor team. |
#' |SEASON |character |Season identifier (4-digit year or 'YYYY-YY' string). |
#' |LIVE_PERIOD |character |Live period. |
#' |LIVE_PC_TIME |character |Time / clock value. |
#' |NATL_TV_BROADCASTER_ABBREVIATION |character |Natl tv broadcaster abbreviation. |
#' |LIVE_PERIOD_TIME_BCAST |character |Live period time bcast. |
#' |WH_STATUS |character |Wh status. |
#'
#' @name wnba_boxscoresummaryv2_game_summary_schema
#' @keywords internal
NULL

#' Shared column schema: wnba boxscoresummaryv2 last meeting schema
#'
#' Columns shared verbatim across: wnba_boxscoresummaryv2, wnba_scoreboard, wnba_scoreboardv2.
#'
#' |col_name |types |description |
#' |:--------------------------------|:---------|:-----------------------|
#' |GAME_ID |character |Unique game identifier. |
#' |LAST_GAME_ID |character | |
#' |LAST_GAME_DATE_EST |character | |
#' |LAST_GAME_HOME_TEAM_ID |character | |
#' |LAST_GAME_HOME_TEAM_CITY |character | |
#' |LAST_GAME_HOME_TEAM_NAME |character | |
#' |LAST_GAME_HOME_TEAM_ABBREVIATION |character | |
#' |LAST_GAME_HOME_TEAM_POINTS |character | |
#' |LAST_GAME_VISITOR_TEAM_ID |character | |
#' |LAST_GAME_VISITOR_TEAM_CITY |character | |
#' |LAST_GAME_VISITOR_TEAM_NAME |character | |
#' |LAST_GAME_VISITOR_TEAM_CITY1 |character | |
#' |LAST_GAME_VISITOR_TEAM_POINTS |character | |
#'
#' @name wnba_boxscoresummaryv2_last_meeting_schema
#' @keywords internal
NULL

#' Shared column schema: wnba boxscoresummaryv2 season series schema
#'
#' Columns shared verbatim across: wnba_boxscoresummaryv2, wnba_scoreboard, wnba_scoreboardv2.
#'
#' |col_name |types |description |
#' |:----------------|:---------|:------------------------------------|
#' |GAME_ID |character |Unique game identifier. |
#' |HOME_TEAM_ID |character |Unique identifier for the home team. |
#' |VISITOR_TEAM_ID |character |Unique identifier for visitor team. |
#' |GAME_DATE_EST |character |Game date est. |
#' |HOME_TEAM_WINS |character |Home team's team wins. |
#' |HOME_TEAM_LOSSES |character |Home team's team losses. |
#' |SERIES_LEADER |character | |
#'
#' @name wnba_boxscoresummaryv2_season_series_schema
#' @keywords internal
NULL

#' Shared column schema: wnba homepagev2 home page stat1 schema
#'
#' Columns shared verbatim across: wnba_homepagev2, wnba_leaderstiles.
#'
#' |col_name |types |description |
#' |:-----------------|:---------|:-----------------------------------------------------------|
#' |RANK |character |Whether to include statistical ranks in the returned table. |
#' |TEAM_ID |character |Unique team identifier. |
#' |TEAM_ABBREVIATION |character |Short team abbreviation (e.g. 'LAS'). |
#' |TEAM_NAME |character |Full team display name (e.g. 'Las Vegas Aces'). |
#' |PTS |character |Points scored. |
#'
#' @name wnba_homepagev2_home_page_stat1_schema
#' @keywords internal
NULL

#' Shared column schema: wnba leaguedashteamclutch league dash team clutch schema
#'
#' Columns shared verbatim across: wnba_leaguedashteamclutch, wnba_leaguedashteamstats.
#'
#' |col_name |types |description |
#' |:---------------|:---------|:-----------------------------------------------|
#' |TEAM_ID |character |Unique team identifier. |
#' |TEAM_NAME |character |Full team display name (e.g. 'Las Vegas Aces'). |
#' |GP |character |Games played. |
#' |W |character |Wins. |
#' |L |character |Losses. |
#' |W_PCT |character |Wins percentage (0-1 decimal). |
#' |MIN |character |Minutes played. |
#' |FGM |character |Field goals made. |
#' |FGA |character |Field goal attempts. |
#' |FG_PCT |character |Field goal percentage (0-1). |
#' |FG3M |character |Three-point field goals made. |
#' |FG3A |character |Three-point field goal attempts. |
#' |FG3_PCT |character |Three-point field goal percentage (0-1). |
#' |FTM |character |Free throws made. |
#' |FTA |character |Free throw attempts. |
#' |FT_PCT |character |Free throw percentage (0-1). |
#' |OREB |character |Offensive rebounds. |
#' |DREB |character |Defensive rebounds. |
#' |REB |character |Total rebounds. |
#' |AST |character |Assists. |
#' |TOV |character |Turnovers. |
#' |STL |character |Steals. |
#' |BLK |character |Blocks. |
#' |BLKA |character | |
#' |PF |character |Personal fouls. |
#' |PFD |character | |
#' |PTS |character |Points scored. |
#' |PLUS_MINUS |character |Plus/minus point differential while on court. |
#' |GP_RANK |character | |
#' |W_RANK |character | |
#' |L_RANK |character | |
#' |W_PCT_RANK |character | |
#' |MIN_RANK |character | |
#' |FGM_RANK |character | |
#' |FGA_RANK |character | |
#' |FG_PCT_RANK |character | |
#' |FG3M_RANK |character | |
#' |FG3A_RANK |character | |
#' |FG3_PCT_RANK |character | |
#' |FTM_RANK |character | |
#' |FTA_RANK |character | |
#' |FT_PCT_RANK |character | |
#' |OREB_RANK |character | |
#' |DREB_RANK |character | |
#' |REB_RANK |character | |
#' |AST_RANK |character | |
#' |TOV_RANK |character | |
#' |STL_RANK |character | |
#' |BLK_RANK |character | |
#' |BLKA_RANK |character | |
#' |PF_RANK |character | |
#' |PFD_RANK |character | |
#' |PTS_RANK |character | |
#' |PLUS_MINUS_RANK |character | |
#'
#' @name wnba_leaguedashteamclutch_league_dash_team_clutch_schema
#' @keywords internal
NULL

#' Shared column schema: wnba on off schema
#'
#' Columns shared verbatim across: wnba_leagueplayerondetails, wnba_teamplayeronoffdetails, wnba_teamvsplayer.
#'
#' |col_name |types |description |
#' |:-----------------|:---------|:-----------------------------------------------|
#' |GROUP_SET |character | |
#' |TEAM_ID |character |Unique team identifier. |
#' |TEAM_ABBREVIATION |character |Short team abbreviation (e.g. 'LAS'). |
#' |TEAM_NAME |character |Full team display name (e.g. 'Las Vegas Aces'). |
#' |VS_PLAYER_ID |character | |
#' |VS_PLAYER_NAME |character | |
#' |COURT_STATUS |character | |
#' |GP |character |Games played. |
#' |W |character |Wins. |
#' |L |character |Losses. |
#' |W_PCT |character |Wins percentage (0-1 decimal). |
#' |MIN |character |Minutes played. |
#' |FGM |character |Field goals made. |
#' |FGA |character |Field goal attempts. |
#' |FG_PCT |character |Field goal percentage (0-1). |
#' |FG3M |character |Three-point field goals made. |
#' |FG3A |character |Three-point field goal attempts. |
#' |FG3_PCT |character |Three-point field goal percentage (0-1). |
#' |FTM |character |Free throws made. |
#' |FTA |character |Free throw attempts. |
#' |FT_PCT |character |Free throw percentage (0-1). |
#' |OREB |character |Offensive rebounds. |
#' |DREB |character |Defensive rebounds. |
#' |REB |character |Total rebounds. |
#' |AST |character |Assists. |
#' |TOV |character |Turnovers. |
#' |STL |character |Steals. |
#' |BLK |character |Blocks. |
#' |BLKA |character | |
#' |PF |character |Personal fouls. |
#' |PFD |character | |
#' |PTS |character |Points scored. |
#' |PLUS_MINUS |character |Plus/minus point differential while on court. |
#' |GP_RANK |character | |
#' |W_RANK |character | |
#' |L_RANK |character | |
#' |W_PCT_RANK |character | |
#' |MIN_RANK |character | |
#' |FGM_RANK |character | |
#' |FGA_RANK |character | |
#' |FG_PCT_RANK |character | |
#' |FG3M_RANK |character | |
#' |FG3A_RANK |character | |
#' |FG3_PCT_RANK |character | |
#' |FTM_RANK |character | |
#' |FTA_RANK |character | |
#' |FT_PCT_RANK |character | |
#' |OREB_RANK |character | |
#' |DREB_RANK |character | |
#' |REB_RANK |character | |
#' |AST_RANK |character | |
#' |TOV_RANK |character | |
#' |STL_RANK |character | |
#' |BLK_RANK |character | |
#' |BLKA_RANK |character | |
#' |PF_RANK |character | |
#' |PFD_RANK |character | |
#' |PTS_RANK |character | |
#' |PLUS_MINUS_RANK |character | |
#'
#' @name wnba_on_off_schema
#' @keywords internal
NULL

#' Shared column schema: wnba player dashboard schema
#'
#' Columns shared verbatim across: wnba_playerdashboardbyclutch, wnba_playerdashboardbygamesplits, wnba_playerdashboardbygeneralsplits, wnba_playerdashboardbylastngames, wnba_playerdashboardbyopponent, wnba_playerdashboardbyteamperformance.
#'
#' |col_name |types |description |
#' |:---------------------|:---------|:---------------------------------------------|
#' |GROUP_SET |character | |
#' |GROUP_VALUE |character | |
#' |GP |character |Games played. |
#' |W |character |Wins. |
#' |L |character |Losses. |
#' |W_PCT |character |Wins percentage (0-1 decimal). |
#' |MIN |character |Minutes played. |
#' |FGM |character |Field goals made. |
#' |FGA |character |Field goal attempts. |
#' |FG_PCT |character |Field goal percentage (0-1). |
#' |FG3M |character |Three-point field goals made. |
#' |FG3A |character |Three-point field goal attempts. |
#' |FG3_PCT |character |Three-point field goal percentage (0-1). |
#' |FTM |character |Free throws made. |
#' |FTA |character |Free throw attempts. |
#' |FT_PCT |character |Free throw percentage (0-1). |
#' |OREB |character |Offensive rebounds. |
#' |DREB |character |Defensive rebounds. |
#' |REB |character |Total rebounds. |
#' |AST |character |Assists. |
#' |TOV |character |Turnovers. |
#' |STL |character |Steals. |
#' |BLK |character |Blocks. |
#' |BLKA |character | |
#' |PF |character |Personal fouls. |
#' |PFD |character | |
#' |PTS |character |Points scored. |
#' |PLUS_MINUS |character |Plus/minus point differential while on court. |
#' |NBA_FANTASY_PTS |character | |
#' |DD2 |character | |
#' |TD3 |character | |
#' |WNBA_FANTASY_PTS |character | |
#' |GP_RANK |character | |
#' |W_RANK |character | |
#' |L_RANK |character | |
#' |W_PCT_RANK |character | |
#' |MIN_RANK |character | |
#' |FGM_RANK |character | |
#' |FGA_RANK |character | |
#' |FG_PCT_RANK |character | |
#' |FG3M_RANK |character | |
#' |FG3A_RANK |character | |
#' |FG3_PCT_RANK |character | |
#' |FTM_RANK |character | |
#' |FTA_RANK |character | |
#' |FT_PCT_RANK |character | |
#' |OREB_RANK |character | |
#' |DREB_RANK |character | |
#' |REB_RANK |character | |
#' |AST_RANK |character | |
#' |TOV_RANK |character | |
#' |STL_RANK |character | |
#' |BLK_RANK |character | |
#' |BLKA_RANK |character | |
#' |PF_RANK |character | |
#' |PFD_RANK |character | |
#' |PTS_RANK |character | |
#' |PLUS_MINUS_RANK |character | |
#' |NBA_FANTASY_PTS_RANK |character | |
#' |DD2_RANK |character | |
#' |TD3_RANK |character | |
#' |WNBA_FANTASY_PTS_RANK |character | |
#'
#' @name wnba_player_dashboard_schema
#' @keywords internal
NULL

#' Shared column schema: wnba playercareerstats season rankings schema
#'
#' Columns shared verbatim across: wnba_playercareerstats, wnba_playerprofilev2.
#'
#' |col_name |types |description |
#' |:-----------------|:---------|:-------------------------------------|
#' |PLAYER_ID |character |Unique player identifier. |
#' |SEASON_ID |character |Unique season identifier. |
#' |LEAGUE_ID |character |League identifier ('10' = WNBA). |
#' |TEAM_ID |character |Unique team identifier. |
#' |TEAM_ABBREVIATION |character |Short team abbreviation (e.g. 'LAS'). |
#' |PLAYER_AGE |character | |
#' |GP |character |Games played. |
#' |GS |character |Games started. |
#' |RANK_MIN |character | |
#' |RANK_FGM |character | |
#' |RANK_FGA |character | |
#' |RANK_FG_PCT |character | |
#' |RANK_FG3M |character | |
#' |RANK_FG3A |character | |
#' |RANK_FG3_PCT |character | |
#' |RANK_FTM |character | |
#' |RANK_FTA |character | |
#' |RANK_FT_PCT |character | |
#' |RANK_OREB |character | |
#' |RANK_DREB |character | |
#' |RANK_REB |character | |
#' |RANK_AST |character | |
#' |RANK_STL |character | |
#' |RANK_BLK |character | |
#' |RANK_TOV |character | |
#' |RANK_PTS |character | |
#' |RANK_EFF |character | |
#'
#' @name wnba_playercareerstats_season_rankings_schema
#' @keywords internal
NULL

#' Shared column schema: wnba playercareerstats season totals schema
#'
#' Columns shared verbatim across: wnba_playercareerstats, wnba_playerprofilev2.
#'
#' |col_name |types |description |
#' |:-----------------|:---------|:----------------------------------------|
#' |PLAYER_ID |character |Unique player identifier. |
#' |SEASON_ID |character |Unique season identifier. |
#' |LEAGUE_ID |character |League identifier ('10' = WNBA). |
#' |TEAM_ID |character |Unique team identifier. |
#' |TEAM_ABBREVIATION |character |Short team abbreviation (e.g. 'LAS'). |
#' |PLAYER_AGE |character | |
#' |GP |character |Games played. |
#' |GS |character |Games started. |
#' |MIN |character |Minutes played. |
#' |FGM |character |Field goals made. |
#' |FGA |character |Field goal attempts. |
#' |FG_PCT |character |Field goal percentage (0-1). |
#' |FG3M |character |Three-point field goals made. |
#' |FG3A |character |Three-point field goal attempts. |
#' |FG3_PCT |character |Three-point field goal percentage (0-1). |
#' |FTM |character |Free throws made. |
#' |FTA |character |Free throw attempts. |
#' |FT_PCT |character |Free throw percentage (0-1). |
#' |OREB |character |Offensive rebounds. |
#' |DREB |character |Defensive rebounds. |
#' |REB |character |Total rebounds. |
#' |AST |character |Assists. |
#' |STL |character |Steals. |
#' |BLK |character |Blocks. |
#' |TOV |character |Turnovers. |
#' |PF |character |Personal fouls. |
#' |PTS |character |Points scored. |
#'
#' @name wnba_playercareerstats_season_totals_schema
#' @keywords internal
NULL

#' Shared column schema: wnba players on court schema
#'
#' Columns shared verbatim across: .players_on_court, wnba_pbps.
#'
#' |col_name |types |description |
#' |:-------------------------|:---------|:-------------------------------------------------------|
#' |game_id |character |Unique game identifier. |
#' |event_num |character |Sequential event number within the game (V2 PBP). |
#' |event_type |character |Event / play type code (V2 PBP). |
#' |event_action_type |character |Numeric event-action-type code (V2 PBP). |
#' |period |numeric |Period of the game (1-4 quarters; 5+ for OT). |
#' |minute_game |numeric |Minute game. |
#' |time_remaining |numeric |Time remaining. |
#' |wc_time_string |character |Wc time string. |
#' |time_quarter |character |Time quarter. |
#' |minute_remaining_quarter |numeric |Minute remaining quarter. |
#' |seconds_remaining_quarter |numeric |Seconds remaining quarter. |
#' |home_description |character |Home team's description. |
#' |neutral_description |character |Neutral description. |
#' |visitor_description |character |Visitor description. |
#' |score |character |Final score. |
#' |away_score |numeric |Away team score at the time of the play. |
#' |home_score |numeric |Home team score at the time of the play. |
#' |score_margin |character |Score margin. |
#' |person1type |character |Person1type. |
#' |player1_id |character |V2 PBP primary player ID (e.g. shooter / fouler). |
#' |player1_name |character |V2 PBP primary player name. |
#' |player1_team_id |character |Team ID of player1. |
#' |player1_team_city |character |Player1 team city. |
#' |player1_team_nickname |character |Player1 team nickname. |
#' |player1_team_abbreviation |character |Player1 team abbreviation. |
#' |person2type |character |Person2type. |
#' |player2_id |character |V2 PBP secondary player ID (e.g. assister / fouled-by). |
#' |player2_name |character |V2 PBP secondary player name. |
#' |player2_team_id |character |Team ID of player2. |
#' |player2_team_city |character |Player2 team city. |
#' |player2_team_nickname |character |Player2 team nickname. |
#' |player2_team_abbreviation |character |Player2 team abbreviation. |
#' |person3type |character |Person3type. |
#' |player3_id |character |V2 PBP tertiary player ID (e.g. blocker). |
#' |player3_name |character |V2 PBP tertiary player name. |
#' |player3_team_id |character |Team ID of player3. |
#' |player3_team_city |character |Player3 team city. |
#' |player3_team_nickname |character |Player3 team nickname. |
#' |player3_team_abbreviation |character |Player3 team abbreviation. |
#' |video_available_flag |character |Video available flag. |
#' |team_leading |character |Team leading. |
#' |away_player1 |numeric |Away team's player1. |
#' |away_player2 |numeric |Away team's player2. |
#' |away_player3 |numeric |Away team's player3. |
#' |away_player4 |numeric |Away team's player4. |
#' |away_player5 |numeric |Away team's player5. |
#' |home_player1 |numeric |Home team's player1. |
#' |home_player2 |numeric |Home team's player2. |
#' |home_player3 |numeric |Home team's player3. |
#' |home_player4 |numeric |Home team's player4. |
#' |home_player5 |numeric |Home team's player5. |
#'
#' @name wnba_players_on_court_schema
#' @keywords internal
NULL

#' Shared column schema: wnba scoreboard east conf standings by day schema
#'
#' Columns shared verbatim across: wnba_scoreboard, wnba_scoreboardv2.
#'
#' |col_name |types |description |
#' |:-------------|:---------|:--------------------------------------|
#' |TEAM_ID |character |Unique team identifier. |
#' |LEAGUE_ID |character |League identifier ('10' = WNBA). |
#' |SEASON_ID |character |Unique season identifier. |
#' |STANDINGSDATE |character | |
#' |CONFERENCE |character |Filter players or teams by conference. |
#' |TEAM |character |Team-side label or team identifier. |
#' |G |character |Games played. |
#' |W |character |Wins. |
#' |L |character |Losses. |
#' |W_PCT |character |Wins percentage (0-1 decimal). |
#' |HOME_RECORD |character |Home win-loss record. |
#' |ROAD_RECORD |character |Win-loss record for road. |
#'
#' @name wnba_scoreboard_east_conf_standings_by_day_schema
#' @keywords internal
NULL

#' Shared column schema: wnba shooting splits assisted by schema
#'
#' Columns shared verbatim across: wnba_playerdashboardbyshootingsplits, wnba_teamdashboardbyshootingsplits.
#'
#' |col_name |types |description |
#' |:-----------------|:---------|:----------------------------------------|
#' |GROUP_SET |character | |
#' |PLAYER_ID |character |Unique player identifier. |
#' |PLAYER_NAME |character |Player name. |
#' |FGM |character |Field goals made. |
#' |FGA |character |Field goal attempts. |
#' |FG_PCT |character |Field goal percentage (0-1). |
#' |FG3M |character |Three-point field goals made. |
#' |FG3A |character |Three-point field goal attempts. |
#' |FG3_PCT |character |Three-point field goal percentage (0-1). |
#' |EFG_PCT |character |Effective field goal percentage (0-1). |
#' |BLKA |character | |
#' |PCT_AST_2PM |character | |
#' |PCT_UAST_2PM |character | |
#' |PCT_AST_3PM |character | |
#' |PCT_UAST_3PM |character | |
#' |PCT_AST_FGM |character | |
#' |PCT_UAST_FGM |character | |
#' |FGM_RANK |character | |
#' |FGA_RANK |character | |
#' |FG_PCT_RANK |character | |
#' |FG3M_RANK |character | |
#' |FG3A_RANK |character | |
#' |FG3_PCT_RANK |character | |
#' |EFG_PCT_RANK |character | |
#' |BLKA_RANK |character | |
#' |PCT_AST_2PM_RANK |character | |
#' |PCT_UAST_2PM_RANK |character | |
#' |PCT_AST_3PM_RANK |character | |
#' |PCT_UAST_3PM_RANK |character | |
#' |PCT_AST_FGM_RANK |character | |
#' |PCT_UAST_FGM_RANK |character | |
#'
#' @name wnba_shooting_splits_assisted_by_schema
#' @keywords internal
NULL

#' Shared column schema: wnba shooting splits schema
#'
#' Columns shared verbatim across: wnba_playerdashboardbyshootingsplits, wnba_teamdashboardbyshootingsplits.
#'
#' |col_name |types |description |
#' |:-----------------|:---------|:----------------------------------------|
#' |GROUP_SET |character | |
#' |GROUP_VALUE |character | |
#' |FGM |character |Field goals made. |
#' |FGA |character |Field goal attempts. |
#' |FG_PCT |character |Field goal percentage (0-1). |
#' |FG3M |character |Three-point field goals made. |
#' |FG3A |character |Three-point field goal attempts. |
#' |FG3_PCT |character |Three-point field goal percentage (0-1). |
#' |EFG_PCT |character |Effective field goal percentage (0-1). |
#' |BLKA |character | |
#' |PCT_AST_2PM |character | |
#' |PCT_UAST_2PM |character | |
#' |PCT_AST_3PM |character | |
#' |PCT_UAST_3PM |character | |
#' |PCT_AST_FGM |character | |
#' |PCT_UAST_FGM |character | |
#' |FGM_RANK |character | |
#' |FGA_RANK |character | |
#' |FG_PCT_RANK |character | |
#' |FG3M_RANK |character | |
#' |FG3A_RANK |character | |
#' |FG3_PCT_RANK |character | |
#' |EFG_PCT_RANK |character | |
#' |BLKA_RANK |character | |
#' |PCT_AST_2PM_RANK |character | |
#' |PCT_UAST_2PM_RANK |character | |
#' |PCT_AST_3PM_RANK |character | |
#' |PCT_UAST_3PM_RANK |character | |
#' |PCT_AST_FGM_RANK |character | |
#' |PCT_UAST_FGM_RANK |character | |
#'
#' @name wnba_shooting_splits_schema
#' @keywords internal
NULL

#' Shared column schema: wnba shotchartdetail league averages schema
#'
#' Columns shared verbatim across: wnba_shotchartdetail, wnba_shotchartleaguewide, wnba_shotchartlineupdetail.
#'
#' |col_name |types |description |
#' |:---------------|:---------|:---------------------------------------------------------------------|
#' |GRID_TYPE |character | |
#' |SHOT_ZONE_BASIC |character |Shot zone (e.g. 'Restricted Area', 'Mid-Range', 'Above the Break 3'). |
#' |SHOT_ZONE_AREA |character |Shot zone area ('Left Side', 'Right Side', 'Center'). |
#' |SHOT_ZONE_RANGE |character |Shot zone range ('Less Than 8 ft.', '8-16 ft.', '16-24 ft.', etc.). |
#' |FGA |character |Field goal attempts. |
#' |FGM |character |Field goals made. |
#' |FG_PCT |character |Field goal percentage (0-1). |
#'
#' @name wnba_shotchartdetail_league_averages_schema
#' @keywords internal
NULL

#' Shared column schema: wnba team dashboard schema
#'
#' Columns shared verbatim across: wnba_teamdashboardbyclutch, wnba_teamdashboardbygamesplits, wnba_teamdashboardbylastngames, wnba_teamdashboardbyopponent, wnba_teamdashboardbyteamperformance, wnba_teamdashboardbyyearoveryear.
#'
#' |col_name |types |description |
#' |:---------------|:---------|:---------------------------------------------|
#' |GROUP_SET |character | |
#' |GROUP_VALUE |character | |
#' |GP |character |Games played. |
#' |W |character |Wins. |
#' |L |character |Losses. |
#' |W_PCT |character |Wins percentage (0-1 decimal). |
#' |MIN |character |Minutes played. |
#' |FGM |character |Field goals made. |
#' |FGA |character |Field goal attempts. |
#' |FG_PCT |character |Field goal percentage (0-1). |
#' |FG3M |character |Three-point field goals made. |
#' |FG3A |character |Three-point field goal attempts. |
#' |FG3_PCT |character |Three-point field goal percentage (0-1). |
#' |FTM |character |Free throws made. |
#' |FTA |character |Free throw attempts. |
#' |FT_PCT |character |Free throw percentage (0-1). |
#' |OREB |character |Offensive rebounds. |
#' |DREB |character |Defensive rebounds. |
#' |REB |character |Total rebounds. |
#' |AST |character |Assists. |
#' |TOV |character |Turnovers. |
#' |STL |character |Steals. |
#' |BLK |character |Blocks. |
#' |BLKA |character | |
#' |PF |character |Personal fouls. |
#' |PFD |character | |
#' |PTS |character |Points scored. |
#' |PLUS_MINUS |character |Plus/minus point differential while on court. |
#' |GP_RANK |character | |
#' |W_RANK |character | |
#' |L_RANK |character | |
#' |W_PCT_RANK |character | |
#' |MIN_RANK |character | |
#' |FGM_RANK |character | |
#' |FGA_RANK |character | |
#' |FG_PCT_RANK |character | |
#' |FG3M_RANK |character | |
#' |FG3A_RANK |character | |
#' |FG3_PCT_RANK |character | |
#' |FTM_RANK |character | |
#' |FTA_RANK |character | |
#' |FT_PCT_RANK |character | |
#' |OREB_RANK |character | |
#' |DREB_RANK |character | |
#' |REB_RANK |character | |
#' |AST_RANK |character | |
#' |TOV_RANK |character | |
#' |STL_RANK |character | |
#' |BLK_RANK |character | |
#' |BLKA_RANK |character | |
#' |PF_RANK |character | |
#' |PFD_RANK |character | |
#' |PTS_RANK |character | |
#' |PLUS_MINUS_RANK |character | |
#'
#' @name wnba_team_dashboard_schema
#' @keywords internal
NULL

#' Shared column schema: wnba team summary overall schema
#'
#' Columns shared verbatim across: wnba_teamdashlineups, wnba_teamplayeronoffdetails, wnba_teamplayeronoffsummary.
#'
#' |col_name |types |description |
#' |:-----------------|:---------|:-----------------------------------------------|
#' |GROUP_SET |character | |
#' |GROUP_VALUE |character | |
#' |TEAM_ID |character |Unique team identifier. |
#' |TEAM_ABBREVIATION |character |Short team abbreviation (e.g. 'LAS'). |
#' |TEAM_NAME |character |Full team display name (e.g. 'Las Vegas Aces'). |
#' |GP |character |Games played. |
#' |W |character |Wins. |
#' |L |character |Losses. |
#' |W_PCT |character |Wins percentage (0-1 decimal). |
#' |MIN |character |Minutes played. |
#' |FGM |character |Field goals made. |
#' |FGA |character |Field goal attempts. |
#' |FG_PCT |character |Field goal percentage (0-1). |
#' |FG3M |character |Three-point field goals made. |
#' |FG3A |character |Three-point field goal attempts. |
#' |FG3_PCT |character |Three-point field goal percentage (0-1). |
#' |FTM |character |Free throws made. |
#' |FTA |character |Free throw attempts. |
#' |FT_PCT |character |Free throw percentage (0-1). |
#' |OREB |character |Offensive rebounds. |
#' |DREB |character |Defensive rebounds. |
#' |REB |character |Total rebounds. |
#' |AST |character |Assists. |
#' |TOV |character |Turnovers. |
#' |STL |character |Steals. |
#' |BLK |character |Blocks. |
#' |BLKA |character | |
#' |PF |character |Personal fouls. |
#' |PFD |character | |
#' |PTS |character |Points scored. |
#' |PLUS_MINUS |character |Plus/minus point differential while on court. |
#' |GP_RANK |character | |
#' |W_RANK |character | |
#' |L_RANK |character | |
#' |W_PCT_RANK |character | |
#' |MIN_RANK |character | |
#' |FGM_RANK |character | |
#' |FGA_RANK |character | |
#' |FG_PCT_RANK |character | |
#' |FG3M_RANK |character | |
#' |FG3A_RANK |character | |
#' |FG3_PCT_RANK |character | |
#' |FTM_RANK |character | |
#' |FTA_RANK |character | |
#' |FT_PCT_RANK |character | |
#' |OREB_RANK |character | |
#' |DREB_RANK |character | |
#' |REB_RANK |character | |
#' |AST_RANK |character | |
#' |TOV_RANK |character | |
#' |STL_RANK |character | |
#' |BLK_RANK |character | |
#' |BLKA_RANK |character | |
#' |PF_RANK |character | |
#' |PFD_RANK |character | |
#' |PTS_RANK |character | |
#' |PLUS_MINUS_RANK |character | |
#'
#' @name wnba_team_summary_overall_schema
#' @keywords internal
NULL

